### ISSUE TITLE
Apparent conflict between line length and vertical alignment

### ISSUE THREAD

**Issue by nrinaudo** [scalameta/scalafmt#1013]
- **Version**: 1.1.0
- **Integration**: sbt, command line
- **Configuration**:
```
style     = defaultWithAlign
maxColumn = 120
```

## Steps

Run scalafmt on the following code:

```scala
object Test {
  def imap[DD](f: D ⇒ DD)(g: DD ⇒ D): Codec[E, DD, F, T] = Codec.from((e: E) ⇒ decode(e).map(f))(g andThen encode)
  def imapEncoded[EE](f: E ⇒ EE)(g: EE ⇒ E): Codec[EE, D, F, T] = Codec.from(g andThen decode)(d ⇒ f(encode(d)))
}
```
## Problem

The output is:
```scala
object Test {
  def imap[DD](f: D ⇒ DD)(g: DD ⇒ D): Codec[E, DD, F, T]        = Codec.from((e: E) ⇒ decode(e).map(f))(g andThen encode)
  def imapEncoded[EE](f: E ⇒ EE)(g: EE ⇒ E): Codec[EE, D, F, T] = Codec.from(g andThen decode)(d ⇒ f(encode(d)))
}
```

Where the `imap` line is exactly 121 characters long, even though the configuration says no line should be over 120.

## Notes

Experimentation seems to show that the `120` limit is usually respected without a problem. My intuition is that this is related to vertical alignment somehow, but I might very well be wrong.

**Comment by olafurpg** [comment]
Vertical alignment doesn't respect maxColumn, or rather maxColumn is unaware of vertical alignment since it happens as a post-process step.

The off-by-one error may be cause by a combination of https://github.com/scalameta/scalafmt/pull/957 and https://github.com/scalameta/scalafmt/pull/982 I may need to revert #957

Related: https://github.com/scala-native/scala-native/pull/927#discussion_r132154613

**Comment by olafurpg** [comment]
This is working as expected, if someone wants to extend vertical alignment to respect maxColumn then please reopen :)
