### ISSUE TITLE
Bug: AvoidInfix breaks compilation

### ISSUE THREAD

**Issue by Dveim** [scalameta/scalafmt#1047]
- **Version**: 1.2.0
- **Integration**: brew
- **Configuration**:
```
...
rewrite.rules = [AvoidInfix]
```

## Steps

I ran scalafmt like this:

```bash
scalafmt
```

## Problem

Before:
```scala
case class I(i: java.time.Instant)
val i: Ordering[I] = Ordering.fromLessThan(_.i isAfter _.i)
```

Scalafmt formats code like this:
```scala
case class I(i: java.time.Instant)
val i: Ordering[I] = Ordering.fromLessThan(_.i.isAfter(_.i))
```

## Expectation

I would like the formatted output to look like this:
```scala
case class I(i: java.time.Instant)
val i: Ordering[I] = Ordering.fromLessThan{ (i1, i2) => i1.i.isAfter(i2.i) } // or whatever compiling
```

**Comment by olafurpg** [comment]
Thank you for reporting! We took a stab at this issue today at the Scala Center Open Source Spree but found it difficult to find the cases where this bug is triggered. The best I can come up with is to mimic eta expansion and cancel the rewrite if the placeholders are more than one.

The expected output should be that the rewrite does nothing here, since a syntactic tool should not insert new names into scope IMO.

**Comment by olafurpg** [comment]
Superseded by #1196
