### ISSUE TITLE
Force newline before EOF

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalafmt#1054]
I just noticed that scalafmt does not force files to end with a newline before the end of files. It should do that by default, without an option to avoid it.

**Comment by nodkrot** [comment]
Any updates?

**Comment by olafurpg** [comment]
No updates, haven't looked at this yet but it's still bugging me almost daily 😅

**Comment by calvinbrown085** [comment]
@olafurpg I'd love to work on this issue, is there a good place to start looking? I'm pretty new to this repository

**Comment by olafurpg** [comment]
That's awesome @calvinbrown085 ! The best start would be to reproduce the issue in a test, I once tried to reproduce the issue in `FormatTests` but failed and didn't investigate further. I haven't tried to setup a `CliTest` like here
https://github.com/scalameta/scalafmt/blob/295cee602b9bd6fb1fd6a2aa4aef5a808f272848/scalafmt-tests/src/test/scala/org/scalafmt/cli/CliTest.scala#L330-L347

I'm fine with creating a custom test suite for this particular issue as well. Let me know if you have any more questions!

**Comment by slavaschmidt** [comment]
Surprisingly, there is a rule for this and the new line is added to the to the code by the main `format` method. 
I've checked with "com.lucidchart" % "sbt-scalafmt-coursier" % "1.12" sbt plugin and the new line also appended after executing `scalafmt` sbt command.
Because of this I suspect this is issue either fixed already or only appear in some specific circumstances.

**Comment by olafurpg** [comment]
Unable to reproduce with the latest version, closing as fixed
