### ISSUE TITLE
Scalafmt errors on future keywords

### ISSUE THREAD

**Issue by Katrix** [scalameta/scalafmt#1063]
This template is a guideline, not a strict requirement.
- **Version**: 1.3
- **Integration**: IntelliJ and Standalone
- **Configuration**: Empty

## Steps

I ran scalafmt like this:

```bash
scalafmt test.scala
```

Content of test.scala
```
class ErrorClass(inline: Boolean)
``` 

## Problem

Receive this error
```
<input>:1: error: identifier expected but : found
class ErrorClass(inline: Boolean)
```

## Expectation

It formats correctly

## Workaround

Place ticks around inline

## Notes

Inline is currently not a keyword for me as I'm not using the macroparadise 3.0.0 plugin. I can't think of a good solution for the standalone version, but it would be neat if the IntelliJ version could pick up the dialect to use from the project.

**Comment by olafurpg** [comment]
Can you try `runner.dialect = Scala211`? This will unfortunately disable parsing trailing commas, but that can be fixed by adding Scala212 to https://github.com/scalameta/scalafmt/blob/d2f968b943a5982dd2f24ec8763af19cd9e7149e/scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtConfDecoders.scala#L28
