### ISSUE TITLE
Wrong indent for empty function literal

### ISSUE THREAD

**Issue by Atry** [scalameta/scalafmt#1104]
This template is a guideline, not a strict requirement.
- **Version**: 1.4.0
- **Integration**: IntelliJ
- **Configuration**:
```
```

## Steps

Given code like this:
```scala
val f: () => Unit = { () => }
```

When I run scalafmt like this:
* Press the format hotkey

## Problem

Scalafmt formats code like this:
```scala
val f: () => Unit = { () =>
  }
```

## Expectation

I would like the formatted output to look like this:
```scala
val f: () => Unit = { () => }
```

**Comment by olafurpg** [comment]
Thanks for reporting! This is accidentally intentional, I was planning to fix it as some point but I started liking it because I think empty blocks signal something unusual is happening that merits a comment. I agree the expected output makes more sense and I'm happy to merge a PR changing the behavior, but I will likely not work on this myself.

**Comment by olafurpg** [comment]
#1180 changed the behavior to produce
```
val f: () => Unit = { () =>
}
```
The closing curly brace is no longer indented by 2 spaces.

I don't have a strong opinion if it should be

```
val f: () => Unit = { () => }
```
instead. Scalafmt in general favors multiple lines for blocks, for better or worse.
