### ISSUE TITLE
Shade Scalameta v1 in sbt-scalafmt

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalafmt#1113]
Scalafmt is currently using Scalameta v1 and Scalafix uses v2. See https://github.com/scalameta/scalafmt/issues/975 for the ticket on upgrading Scalafmt to v2. However, 

* I don't know when me or someone else will get around to upgrade
* there is a growing need to be able to use sbt-scalafmt and sbt-scalafix together but by default this will not work due to class incompatibilities between Scalameta v1 and v2.

As a temporary relief, we could publish sbt-scalafmt with the following packages shaded

* scala.meta
* metaconfig
* org.langmeta (maybe not necessary)

Additionally, we may need to exclude scalapb from the scalafmt's transitive dependencies. Scalafmt doesn't use it but it's brought in transitively. This workaround would allow sbt-scalafix and sbt-scalafmt to live happily together on the same classpath without doing classloading hacks in sbt-scalafix.

**Comment by fommil** [comment]
@alexarchambault TL;DR if `sbt-scalafmt` shaded `scala.meta` then we'd be able to have a much more efficient `sbt-scalafix` and avoid classpath nonsense. Do you think it'd be hard to do this?

**Comment by alexarchambault** [comment]
scala-meta shoudn't rely much on reflection, so I guess that should work… There's an example of how to do that in coursier see around [here](https://github.com/coursier/coursier/blob/834f59b4654c5c7aee01b297e477206ad8c37313/build.sbt#L8-L21) and [here](https://github.com/coursier/coursier/blob/b093c77193c60ec65851fb5f5a8ccaeb1f3e1237/project/Settings.scala#L231-L242).

Note that the `shadeNamespaces` setting is optional. It only aims at speeding things by shading whole namespaces rather than by shading the classes found in it one-by-one. But one has to be sure that all classes from that namespace are indeed in the shaded dependencies.

**Comment by pauldraper** [comment]
This is one of the cases where separate classloader (e.g. the approach of https://github.com/lucidsoftware/neo-sbt-scalafmt) helps.

**Comment by fommil** [comment]
That brings is own problems, the multiple classloaders are unusable on large projects because of memory.

**Comment by olafurpg** [comment]
I am leaning towards biting the bullet and upgrade to meta v3. I already take the first steps in this direction in #1145. Shading the dependency is not a long term solution

**Comment by fommil** [comment]
that's awesome news!
