### ISSUE TITLE
Feature Request: add option to enable for new projects if .scalafmt.conf is found.

### ISSUE THREAD

**Issue by ShaneDelmore** [scalameta/scalafmt#1129]
Scalafmt intellij plugin works wonderfully if you remember to enable it but in an environment where I open many projects per day I have noticed that I keep forgetting to enable scalafmt on projects that support it.  I may not want to automatically use scalafmt with the default config if scalafmt is not used on a specific project, but if scalafmt is used by a project (as indicated by the presence of a scalafmt.conf) then I always want to use it for formatting.

**Comment by olafurpg** [comment]
Do you mean automatically "format on save" if there is a .scalafmt.conf? I think this would be a great idea.

The relevant piece of code is here https://github.com/scalameta/scalafmt/blob/3b6b8f23e72a0d4f260c131d564aa2d824eea67e/scalafmt-intellij/src/main/scala/org/scalafmt/intellij/IdeaSettings.scala#L14

Any chance you would be tempted to take a stab at this? If not, I am inclined to close this in favor of https://youtrack.jetbrains.com/issue/SCL-13658 since in the long-term I would like the intellij plugin to be builtin with the intellij scala plugin.

**Comment by ShaneDelmore** [comment]
I’ll take a look.

**Comment by ShaneDelmore** [comment]
No, I haven’t and won’t be able to for at least a week.  Found a new apartment finally! But that will keep me busy moving all week.

**Comment by olafurpg** [comment]
@ShaneDelmore The latest EAP for the IntelliJ Scala plugin has builtin scalafmt support with automatic detection of .scalafmt.conf. I just upgraded and got the following dialogue on startup
![screen shot 2018-07-16 at 16 58 45](https://user-images.githubusercontent.com/1408093/42766016-a3fcd106-8919-11e8-84d9-8b3dd8a22f96.png)

Do you think we should close this ticket in favor of the builtin scalafmt support in IntelliJ?
