### ISSUE TITLE
Better examples in the documentation on how to use the scalafmt.conf

### ISSUE THREAD

**Issue by ricardogaspar2** [scalameta/scalafmt#1130]
This template is a guideline, not a strict requirement.
- **Version**: 1.4.0
- **Integration**: IntelliJ
- **Configuration**:
```
maxColumn = 100
```

## Notes
You could have a better documentation to point out some examples of scalafmt.conf.
At least is not easy to find it...
In the documentation website it is only presented how the code will look like but not how to do it. It shows multiple settings/tags that can be changed, but it's not clear enough.
I'm trying to look in the documentation how to use the intellijStyle configuration , but I only find some example of a scalafmt.conf in another website:
https://copperlight.github.io/scala/scalafmt-configuration-tips/

It can be my mistake to not find clear examples in this repo nor the [documentation website](http://scalameta.org/scalafmt/#style )

**Comment by olafurpg** [comment]
Thanks for reporting. The lack of docs for configuration are due to my originally naive hope that people would be happy with the defaults!

Would you be tempted to contribute more examples to the docs? The code listing are automatically generated with normal  scala code here
https://github.com/scalameta/scalafmt/blob/b5b25e13aeaa05e8d17422f4f512971e2619b918/readme/src/main/scala/org/scalafmt/readme/Readme.scala#L123
and invoked from the docs here
 https://github.com/scalameta/scalafmt/blob/master/readme/Configuration.scalatex
using http://www.lihaoyi.com/Scalatex/

**Comment by ricardogaspar2** [comment]
Hi @olafurpg , I not fluent in scala, i'm just a beginner so I think I cannot help much...
But it would be very useful to have such examples; specially the intelliJ style you refer in the docs.

**Comment by olafurpg** [comment]
That could be a good ticket for the spree on Wednesday! The underlying data
structure is a json adt so it should be possible to compute the diff from
the default settings.

I've been meaning to have a mode in the cli to automatically remove
explicitly written default settings in .scalafmt.conf

**Comment by ShaneDelmore** [comment]
I would have thought you would have the opposite, a way to push defaults into .scalafmt.conf so when you change the defaults you don’t change existing formatting.

**Comment by olafurpg** [comment]
@mads-hartmann has done a great job to make configuration examples on the website easier to understand with minimal copy-paste config next to code examples. Not all of the examples on the website have been ported to this layout, but I hope that will be done alongside #1146
