### ISSUE TITLE
Option to skip shebang lines for Scala shell scripts

### ISSUE THREAD

**Issue by FlashSheridan** [scalameta/scalafmt#1297]
- **Version**: 1.5.1

## Steps

Given code like this:
```scala
#!/bin/sh
  exec scala "$0" "$@"
  !#
  // Say hello to the first argument
  println("Hello, " + args(0) + "!")
```
(Odersky, Martin. Programming in Scala: A Comprehensive Step-by-Step Guide, Third Edition (Kindle Locations 21737-21739). Artima Press. Kindle Edition.)

When I run scalafmt like this:

```bash
…/scalafmt …/FlashScalaStationery.scala
```

## Problem

Scalafmt reports an error:
```scala
[warn] Error in …/FlashScalaStationery.scala: <input>:1: error: expected class or object definition
#!/bin/sh
^
```

## Expectation

I would like the shebang lines to be skipped, either automatically or with a command-line option, perhaps to skip a certain number of lines.

**Comment by FlashSheridan** [comment]
Even adding `// format: on` at the beginning of the file, per 
https://scalameta.org/scalafmt/docs/configuration.html#format-off (which would of course break the shebang line) has no effect.

**Comment by olafurpg** [comment]
Thanks for reporting! The `.scala` file extension for scala scripts can be problematic for tooling in general because the scripts do not contain valid scala syntax resulting in parse errors. Even if we ignore the shebang, we would still need to customize the parser to accept top-level statements.

Have you tried using ammonite scripts? http://ammonite.io/#ScalaScripts scalafmt treats files with the `.sc` file extension as Scala scripts and parses them accordingly.

**Comment by volth** [comment]
> The `.scala` file extension for scala scripts can be problematic for tooling in general because the scripts do not contain valid scala syntax resulting in parse errors

There is no "problem with tooling  in general", this problem is limited to `scalafmt`
For example IDEA does handle #! ... !# as comment in files with `.scala` file extension, does not fail parsing them and does not try to find Scala keywords within.

Ammonite's `.sc` scripts is not the only case where Scala files have shebangs

**Comment by philwalk** [comment]
I'm still seeing this with version `3.7.14`, here's the rejected shebang line:

```sh
#!/usr/bin/env -S scala @classpathAtfile
```

The script runs just fine with whatever extension I use.
