### ISSUE TITLE
Short annoymous function's closing curly brace is placed on a separate

### ISSUE THREAD

**Issue by redvasily** [scalameta/scalafmt#1311]
This template is a guideline, not a strict requirement.
- **Version**: 1.5.1
- **Integration**: IntelliJ
- **Configuration**:
```
style = IntelliJ
maxColumn = 108
align = none
danglingParentheses = true
```
But the configuration doesn't really seem to matter. I see the same behavior with any configuration I've tried.

## Steps

Given code like this:
```scala
whatever.map { (key, value) => (key, value) }
```

## Problem

Scalafmt formats code like this:
```scala
whatever.map { (key, value) => (key, value)
}
```

## Expectation

I would like the formatted output to look like this:
```scala
whatever.map { (key, value) => (key, value) }
```

Or like this:

```scala
whatever.map { (key, value) => 
  (key, value) 
}
```

## Workaround

The workaround is to use parentheses:

```scala
whatever.map((key, value) => (key, value))
```

But it would be nice if scalafmt could handle the case with curly braces.

**Comment by olafurpg** [comment]
Thanks for reporting! I am unable to reproduce with the v1.5.1 cli, it could be that the cause is the built-in scalafmt support in Intellij which is not recommended to select "continue using IntelliJ formatter" and use the Scalafmt plugin instead https://scalameta.org/scalafmt/docs/installation.html#continue-using-intellij-formatter
