### ISSUE TITLE
Publish new IntelliJ nightly builds

### ISSUE THREAD

**Issue by dwijnand** [scalameta/scalafmt#1351]
It would be lovely to be able to use the 2.0.0 pre-releases in IntelliJ, but the latest nightly builds are for the old 1.6 release: https://plugins.jetbrains.com/plugin/8236-scalafmt

**Comment by ches** [comment]
Looks like a nightly release was published for 2.0.0-RC5 on March 6th via ef17130, so perhaps we can close this.

I'm wondering what the fate of the plugin should be since [IntelliJ Scala plugin's support now uses scalafmt-dynamic][1], but I'll open a new issue about that.

[1]: https://blog.jetbrains.com/scala/2019/03/27/intellij-scala-plugin-2019-1-highlighting-for-comprehensions-find-usages-for-implicits-and-more/#scalafmt
