### ISSUE TITLE
Unable to format due to bug in scalafmt

### ISSUE THREAD

**Issue by grindvoll** [scalameta/scalafmt#1409]
- **Version**: 2.0.0-RC7
- **Integration**: sbt
- **Configuration**:
```
maxColumn = 100
```

## Steps

The following code causes scalafmt to abort with a message "Unable to format due to bug in scalafmt":

```scala
class Sample {
  def mkFunc(flag: Boolean): String => Boolean = {
    if(flag) {
      (v => true)
    } else {
      (v => false)
    }
  }
}
```

By removing the superfluous parenthesis around the functions, the problem disappears. However, it is valid Scala syntax and it would be nice if scalafmt also would accept the code.

**Comment by stephennancekivell** [comment]
FWIW I tried to look into this, and couldnt figure out how to fix it.

I can confirm that the example crashes when running from the command line. However I cant get it to crash in unit tests. I think the issue is in BestFirstSearch.scala.

If anyone has any tips I can more of a look.

https://github.com/stephennancekivell/scalafmt/commit/02d36066c4758cd9d4bc28f12c5b43fd57be4e4b

**Comment by stephennancekivell** [comment]
Ok, I've been able to reproduce the issue in a failing unit test.

I'll put this here incase of help to anyone. Maybe I'll be able get my head around how this code works and fix it one day :)

https://github.com/stephennancekivell/scalafmt/commit/863efeb21b1d2db26aa22d0b9b78c0cf107f99e5

**Comment by kitbellew** [comment]
@stephennancekivell can you please check? i can't reproduce on `master`, either directly or with you CliTest example.

**Comment by kitbellew** [comment]
@grindvoll i can't reproduce this problem. if you can still see it with 2.4.1, please share a larger example with your configuration overrides.
