### ISSUE TITLE
trailing commas "always" does not respect function arity

### ISSUE THREAD

**Issue by russwyte** [scalameta/scalafmt#1410]
This template is a guideline, not a strict requirement.
- **Version**: 2.0.0-RC6
- **Integration**: IntelliJ
- **Configuration**:
```
version = 2.0.0-RC6

align = true

maxColumn = 120

rewrite.rules = [RedundantBraces]

rewrite.redundantBraces.stringInterpolation = true

newlines.alwaysBeforeMultilineDef = true

newlines.alwaysBeforeTopLevelStatements = true

trailingCommas = always

```

## Steps

Given code like this:
```scala
   case Scrolled(key) =>
      resultFor(key) { rts =>
        rts.viewport.fold(noChange) { v =>
          val l = v.top(rts)
          effectOnly(
            Effect.action(
              ActionBatch(
                UpdateReaderState(rts.copy(scrollY = v.scrollY, location = l)),
                FindPageNumber(key)
              )
            )
          )
        }
      }
```

When I run scalafmt like this:

```bash
scalafmt
```

## Problem

Scalafmt formats code like this:
```scala
    case Scrolled(key) =>
      resultFor(key) { rts =>
        rts.viewport.fold(noChange) { v =>
          val l = v.top(rts)
          effectOnly(
            Effect.action(
              ActionBatch(
                UpdateReaderState(rts.copy(scrollY = v.scrollY, location = l)),
                FindPageNumber(key),
              ),
            ),
          )
        }
      }
```

## Expectation

I would like the formatted output to look like this:
```scala
    case Scrolled(key) =>
      resultFor(key) { rts =>
        rts.viewport.fold(noChange) { v =>
          val l = v.top(rts)
          effectOnly(
            Effect.action(
              ActionBatch(
                UpdateReaderState(rts.copy(scrollY = v.scrollY, location = l)),
                FindPageNumber(key),
              )
            )
          )
        }
      }
```

## Workaround

I haven't found any workaround.
## Notes

It seems like trailing commas "always" configuration should respect function/method arity - otherwise it looks like every function/ethod is a var-arg function/method.

**Comment by russwyte** [comment]
In the example above effectOnly and Effect.action can only ever take one argument each - it makes no sense to have comma there. That could be very confusing to developers looking at the source code - even if it does compile. It seems we should only use trailing commas where we can actually pass var-args.

**Comment by russwyte** [comment]
Perhaps an ideal solution here would be to have a 4th option that only applies the rule to var-arg methods/functions? My main concern is code clarity - I don't like an arity(1) function to look like an airty(n) function, but I do want training command for building sequences etc...

**Comment by neko-kai** [comment]
@russwyte @tanishiking 
I think there's no way for scalafmt to know the function arity as it does not compile the code, however what scalafmt could do here is add trailing commas only for multi-argument functions – i.e. add a trailing comma only if there already was a comma in the same parenthese block – never alone – I think from an implementation point of view counting commas may be the easiest to implement and behave quite intuitively for users.

```scala
arg2(
  a,
  b, // <- add comma
)
```
&
```scala
arg1(
  a // <- don't add comma since there were no commas before
)
```

**Comment by tanishiking** [comment]
> I think there's no way for scalafmt to know the function arity as it does not compile the code,

That's right. scalafmt is a syntactic tool, and there's no way to see the number of parameters.
It might be better to develop such a rewrite based on `SemanticRule` of [scalafix](https://scalacenter.github.io/scalafix/docs/developers/tutorial.html) which can retrieve semantic information from semanticdb.

> add a trailing comma only if there already was a comma in the same parentheses block

Yeah, we can do that, but I'm not sure is there a strong demand for that feature. (Personally, in that case, it would be sufficient to set `trailingCommas=preserve` for me). FYI @russwyte

**Comment by neko-kai** [comment]
@tanishiking 
> Yeah, we can do that, but I'm not sure is there a strong demand for that feature. (Personally, in that case, it would be sufficient to set trailingCommas=preserve for me).

Thing is, right now I have to use `trailingCommas=preserve` because scalafmt's current behavior adds too many trailing commas on single-argument call-sites, e.g. everywhere where a lambda is used in parentheses looks strange and, most importantly, a human would never format a lambda like that:
```scala
.flatMap(
  a =>
    b(a),
)
```
The problem with `trailingCommas=preserve` is that you must manually add trailing commas to every argument list – they won't be added automatically, whereas I want trailing commas in natural places, e.g. multi-argument vertical lists, to be added automatically as the default in the codebase. This behavior may not change `trailingCommas=always`, it could be under new config, e.g. `trailingComma=onMultiple` or `trailingComma=inConfigStyle`

**Comment by olafurpg** [comment]
Scalafmt only understands the syntax of the program, it's not able to tell if a method call points to a vararg since that would require compiling the source file with a classpath and compiler options. I agree `always` option is current quite unusable but I'm not sure how we could make it much better, even if you require there to be more than one argument then you still hit on cases where trailing commas get inserted in non-vararg methods
```scala
def add(a: Int, b: Int) = a + b
add(
  a,
  b,
)
```

**Comment by neko-kai** [comment]
@olafurpg 
Personally, a trailing comma in this case is Ok (I could change the method signature and adding an argument then would be better with a trailing comma) - it's just annoying in the case of a single argument function

**Comment by kitbellew** [comment]
@neko-kai @russwyte one reason to use trailing commas has nothing to do with arity, and more with code review readability. if one appends a new parameter to an existing function, a trailing comma leaves the previously last parameter line unchanged and improves change reviewability:

```
  a(
    b,
   )
```
becomes
```
  a(
    b,
    c,
  )
```

(Frankly, I am curious to learn what other possible intent can be behind using trailing commas.)

**Comment by neko-kai** [comment]
@kitbellew Yes, it has nothing to do with arity, but forcing a trailing comma by default on single-parameter lists makes higher-order functions look awful:

```scala
list.map(a =>
  (1 + 2 - a).pipe(transform) / 2,
)
```

and i think that even applies to curly braces:

```scala

list.map {
  a =>
    (1 + 2 - a).pipe(transform) / 2,
}
```

^ double awful. The comma in curlies can't even be useful.

That's why I advocate `preserve`ing commas for single-parameter lists, but `force`ing them only once a second parameter appears.

```scala
either.fold(
  a => b,
  c => d,
)
```

^ commas look fine with lambdas if there are multiple lambda arguments

**Comment by kitbellew** [comment]
@neko-kai i am not privy to the reasoning behind adding trailing commas, but i agree that we do handle single-arg cases differently in various places:
```
  // one
  a(x =>
    y
  )
  a(x =
    y
  )
  // two
  a(
    x => y,
    x => y
  )
  a(
    x = y,
    x = y
  )
```

also, @olafurpg mentioned above that `always` is unusable in the current form. and @gabro introduced it.

so, i don't mind changing behaviour for single-arg cases but will let the esteemed experts chime in on what it will take to make this option usable and sensible.

**Comment by neko-kai** [comment]
@kitbellew 
Yes, I don't think anyone is currently using this option 'in production' currently – and, for me and maybe for others, the only deterrent is the unexpected comma at the end of lambda arguments in single-arg position. With that gone I could enable the option and have uniform trailing commas everywhere, instead of having to manually add them.

**Comment by kitbellew** [comment]
@neko-kai generally, i'd recommend collecting feedback from peers, say, through that gitter channel, before we introduce another solution.

still, how would you format this:
```
  new a(
    b
  )(
    c,
    d
  )
```
(current scalafmt logic would count them as 3 arguments, not 1 + 2).

**Comment by neko-kai** [comment]
@kitbellew 
Ideally, each argument list would be counted separately for this purpose, because it wouldn't make sense to e.g.  add commas for `Option.fold`:
```scala
Option(1).fold(
  None
)(Some(_))
```
So:
```scala
new a(
  b
)(
  c,
  d,
)
```
but
```scala
new a(
  b
)(
  c
)(
  d
)
```

**Comment by kitbellew** [comment]
@neko-kai what about:

```
a(
  b,
  c: _*
)
```

**Comment by neko-kai** [comment]
@kitbellew comma after vararg is non-sensical, but it wouldn't really bother me if it was inserted there

**Comment by kitbellew** [comment]
@neko-kai @olafurpg as it currently stands, `always` is implemented correctly, as it has nothing to do with arity nor varargs; see the document which substantiates the feature https://docs.scala-lang.org/sips/trailing-commas.html

however, we can always replace existing setting with `trailingCommas: Option[Int]` and map `always` to 1, `never` to as a special value of 0 and preserve to omitted. for what @neko-kai wants to do, he can use 2. or just call it `minArity` for clarity.

**Comment by neko-kai** [comment]
@kitbellew @olafurpg 
Actually, reading the document the motivation is related to arity, it says:

> When using a comma-separated sequence of elements on multiple lines, 
> It is inconvenient to remove or comment out elements because the last element mustn’t have a trailing comma:
> It is also inconvenient to reorder because every element but the last one must be followed by a comma:

The very first line talks about a **comma-separated** sequence. To have a comma with old syntax there must be at least 2 elements.
Moreover, the situation with removal of elements doesn't happen with one argument – if you remove the only existing argument, the argument list becomes empty – which is valid syntax there will be no parse error, the parse error ONLY happened with 2 or more elements.
The same goes for the reordering argument – reordering can't be done with only one argument.

As I read it, not only the original motivation has to do with arity, all of the original motivation arguments apply only in the situations with more than one argument – which I argue is exactly where the trailing comma should be inserted to actually reap the cited benefits of the syntax change!

**Comment by kitbellew** [comment]
@neko-kai the document also mentions adding parameters and avoiding changes to existing lines, to minimize diff and preserve blame. so, i wouldn't change what always does today.

**Comment by adampauls** [comment]
I just wanted to chime in and saw that my organization uses `always` and is quite happy with it (after bug fixes from the amazing @kitbellew). I think the new `multiple` option is a reasonable compromise, but I just wanted to point out to @neko-kai that `always` does not insert the comma in the curly brace case above:

```scala
list.map {
  a =>
    (1 + 2 - a).pipe(transform) / 2,
}```

I'm on 2.4.1, and although it won't remove the comma if you put it there, scalafmt will not it insert it. I don't actually understand why scala syntax even allows that trailing comma. I think it was just an oversight in the grammar. `import` statements can have comma-separated lists in curly braces, but all other uses of curlies cannot. In any case, this was fixed in https://github.com/scalameta/scalafmt/pull/1479. For me personally, I like the consistency that any argument list in parens will have the commas, but if you are using a single-arg function, you can use curlies to make it clear that no commas should be inserted. 

In an ideal world (IMHO), scalafmt would be able to get the best all worlds if it automatically switched to curlies for multi-line lambdas, so that you would only ever see

```scala
list.map(a => (1 + 2 - a).pipe(transform) / 2)
```
or

```scala
list.map { a =>
    (1 + 2 - a).pipe(transform) / 2
}
```

with no ugly commas anywhere.

**Comment by neko-kai** [comment]
@adampauls Hmm, I was not aware of that PR, perhaps it addressed my concerns regarding lambdas. I'll try to compare `always` & `multiple` after new scalafmt release and report my expericence here. Massive thanks to @kitbellew for implementing `multiple`!
