### ISSUE TITLE
Deduct the closest-matching settings for available code

### ISSUE THREAD

**Issue by przemek-pokrywka** [scalameta/scalafmt#1423]
As a developer who wants to gently introduce scalafmt to the team I would like the tool to be able to propose a configuration, that fits the existing style the best (generates the smallest possible unified diff when applied to the codebase). The benefits I expect to receive are:
- I save time that I would otherwise spend on fiddling with configuration parameters
- the team enjoys the familiar code style, with additional bonus of consistency being preserved automatically

## Steps

Given code like this:
```scala
// whatever code style is that
```

When I run scalafmt like this:

```bash
scalafmt extract-config
```

## Problem

Scalafmt doesn't produce the list of settings, that match the existing code the best.

## Expectation

I would like the output to look like this:
```
assumeStandardLibraryStripMargin = true
...
```

## Workaround

In theory I could figure out all the setting keys and all possible values for them, generate all possible scalafmt configurations and then, for each of the configurations:
- run the scalafmt on my codebase
- run `git diff | wc` and store the result

Finally I could check which configuration has generated the smallest diff.

**Comment by tanishiking** [comment]
@przemek-pokrywka https://github.com/tanishiking/scalaunfmt may help you to find the "best" settings for the existing code. This tool receives the list of possible settings and existing Scala code, and output the best-match (has smallest Levenstein distance) setting for the existing code.

Unfortunately, this tool doesn't try to generate all possible scalafmt configurations because scalafmt has too much kind of settings and generating all will lead to a combinatorial explosion :|

**Comment by przemek-pokrywka** [comment]
Thanks @tanishiking, wasn't aware of that tool. It goes long way already, great work!
I suspect you're correct with the combinatorial explosion, I'll rethink my approach.
