### ISSUE TITLE
Add `--list` option that outputs names of files changed

### ISSUE THREAD

**Issue by ArturGajowy** [scalameta/scalafmt#1459]
Currently, running:

`scalafmt Foo.scala`

on a non-formatted file outputs:

```
Reformatting...
```

I'd expect it to list all the files that were changed during reformatting, or provide an option to do so.

Similarly, running:

`scalafmt --test Foo.scala`

will output the diffs of files needing formatting - but ideally there'd be an option to just list the names.

**Comment by tanishiking** [comment]
It would be nice for scalafmt to list all the formatted files (if scalafmt receives the list of files to format) without any options 👍

**Comment by ArturGajowy** [comment]
Not sure if I understand: so if run
`scalafmt Foo.scala Bar.scala`
and only Foo.scala changes due to formatting, what would be the output?

If I just run:
`scalafmt`
and that changes just Foo.scala - what would be the the output?

I'm not sure if you mean the outputs to be:
1) `Foo.scala` in both cases
2) `Foo.scala` and `Bar.scala` in the first case, nothing in the second case
?

**Comment by tanishiking** [comment]
- `scalafmt Foo.scala Bar.scala`
  - it should print `Foo.scala` and `Bar.scala` because those two files are the target (even if `Bar.scala` doesn't have any change by scalafmt)
- `scalafmt`
  - it shouldn't show any filenames in any cases.

**Comment by ArturGajowy** [comment]
That would be useful debugging info, but would not help my use case - I'd like to see the files that changed (when running without `--test`) or need changing (when running with `--test`). So I'm after option 1. above.

Maybe there should be two flags: `--list` and `--list-not-formatted`?

**Comment by mroth** [comment]
Also strong want this, and suspect my use case is the same as @ArturGajowy -- I want a list of all files that "would be re-formatted".  In my case, it's because we want to run this in CI, and warn if a file was not scalafmt'd.  The standard "diff" format is useful for writing changes to a file, but not as an error message.

For comparison, similar options with other formatters:

 - `prettier --check` (https://prettier.io/docs/en/cli.html#check)
 - `gofmt -l` (`-l	list files whose formatting differs from gofmt's`)

In the case of Prettier, you then get output such as:
```
Checking formatting...
src/fileA.js
src/fileB.js
Code style issues found in the above file(s). Forgot to run Prettier?
```

This is a much nicer error message to give someone in a CI check than dumping many screens of diffs.

**Comment by tanishiking** [comment]
> I want a list of all files that "would be re-formatted". 

Ah, finally I got it.
It would be nice to have an option `--list` or something whose behavior is equivalent to `gofmt -l` (list files whose formatting differs from scalafmt's)

**Comment by tanishiking** [comment]
Closed by https://github.com/scalameta/scalafmt/pull/1466 👍
