### ISSUE TITLE
Definition indentation tab width doesn't work

### ISSUE THREAD

**Issue by aganm** [scalameta/scalafmt#1493]
Version: 2.0.0-RC4
Integration: VS Code with Scala (Metals) extension
Configuration:
```
  version = "2.0.0-RC4"
  maxColumn = 80
  continuationIndent.callSite = 8
  continuationIndent.defnSite = 8
  continuationIndent.extendSite = 8
```

## Steps

When I run VS code format document (that calls scalafmt), scalafmt formats code like this:
```scala
final class Goods(
        _food: Int = 0, 
        _materials: Int = 0, 
        _products: Int = 0, 
        _fuel: Int = 0 
) {
  var raw = Array(_food, _materials, _products, _fuel)
  def food: Int = raw(0)
  def materials: Int = raw(1)
  def products: Int = raw(2)
  def fuel: Int = raw(3)
  def weight = raw.sum
}
```
## Expectation

I would like the formatted output to look like this:
```scala
final class Goods(
        _food: Int = 0, 
        _materials: Int = 0, 
        _products: Int = 0, 
        _fuel: Int = 0 
) {
        var raw = Array(_food, _materials, _products, _fuel)
        def food: Int = raw(0)
        def materials: Int = raw(1)
        def products: Int = raw(2)
        def fuel: Int = raw(3)
}

**Comment by poslegm** [comment]
There is no config for indentation width. Scalafmt uses 2 spaces indents as it recommended in official Scala [guide](https://docs.scala-lang.org/style/indentation.html). You can only configure indentation of multiline function arguments/contstructor params and `extends` section.

**Comment by sstadick** [comment]
@poslegm, I would potentially be interested in making this configurable. Do you have a sense of how big / feasible this might be? Or is it roadmapped for the near future?

**Comment by olafurpg** [comment]
The block indentation is intentionally not configurable because two space indent is one of the few styling conventions that is pretty much universally accepted in the scala community. I would be inclined to close this ticket with “working as intended”

**Comment by aganm** [comment]
working as intended

**Comment by FFdhorkin** [comment]
since there's no way to override this, I guess we'll look for an alternative to scalafmt. 2 spaces is insufficient for visually scanning indentation. This is a matter of accessibility; 2 spaces is practically invisible indentation, and it makes code reviews much harder.

Too bad, as scalafmt looks great, otherwise. Seems bizarre to me that scalafmt would have 5 overrides for indentation... but not any for the default block indentation. You might as well remove those 5 config options.

**Comment by readren** [comment]
If the block indentation is **intentionally** not configurable, then, at least, clarify it so users who prefer a different value don't spend 10 minutes searching in the documentation and the web a way to configure it.

**Comment by Ichoran** [comment]
With Scala 3 and significant indentation coming, it is essential to allow this to be configurable, as extra block indentation is one of the few ways to help parse nested blocks with significant indentation.  (The other being special editor support with extra-obvious indentation depths.)

Many people like 4 (like Python, which chose 4 because 2 isn't enough to see clearly without braces); Martin actually likes 3.

So please re-open this issue.  This will likely be one of the most desired capabilities for formatting once Scala 3 is out.  (Probably lots of braces + 2 space <=> brace-free + 4 space transformations.)

**Comment by olafurpg** [comment]
@Ichoran There's a related discussion about indentation for the braceless syntax in Scala 3 here https://github.com/scalameta/scalafmt/issues/2385

**Comment by momomo** [comment]
No shit, the same people behind Twitter is the people behind Scala. Both love authority and censorship to the max. To even force this shit because the developer things 2 is the best and should be allowed to be disputed or changed even in personal projects is absurd. I fucking hate this shit language from every part of being. Can it die already?
