### ISSUE TITLE
align.tokens after align=none activates align.ifWhileOpenParen=true

### ISSUE THREAD

**Issue by anilkumarmyla** [scalameta/scalafmt#1496]
This template is a guideline, not a strict requirement.
- **Version**: 2.0.1
- **Integration**: sbt
- **Configuration**:
```
version = 2.0.1
maxColumn = 130
align = none
align.tokens = [
  {code = "%", owner = "Term.ApplyInfix"},
  {code = "%%", owner = "Term.ApplyInfix"}
]
```

## Problem
This config makes `align.ifWhileOpenParen=true` while the default is false

## Expectation
Default should remain the same

## Workaround
We can make it explicitly false
```
align.ifWhileOpenParen = false
```

**Comment by poslegm** [comment]
The problem in the config parsing. `align = none` is the [preset](https://github.com/scalameta/scalafmt/blob/master/scalafmt-core/shared/src/main/scala/org/scalafmt/config/Align.scala#L84) for `Align` values. But if you set some `Align` field manually (`align.tokens` for example) you will dismiss `none` preset and fallback to [default](https://github.com/scalameta/scalafmt/blob/master/scalafmt-core/shared/src/main/scala/org/scalafmt/config/Align.scala#L63) case class values.

So you can't at the same time use `none` or `most` preset and configure single sub-config. There is a choice: use _full_ preset or configure individual parameters explicitly.

I will close this issue because current behavior is not bug in my opinion. Please feel free to reopen it if you want to propose another configuration parsing rules.

**Comment by anilkumarmyla** [comment]
This is in the gray area of having to specify the entire tree of a config node just to toggle one setting, if the defaults of config node don't satisfy your requirements. This is ok for now, can live with it 😄
