### ISSUE TITLE
Scalafmt CLI should ignore .metals/ sources by default

### ISSUE THREAD

**Issue by sloshy** [scalameta/scalafmt#1526]
- **Version**: 2.1.0
- **Integration**: Coursier CLI

## Steps

Given a repository that includes a `.metals/` directory with sources (from code navigation via metals),

When I run scalafmt in the repository root,

## Problem

Scalafmt throws an exception during output:
```
$ scalafmt
Exception in thread "main" java.nio.file.AccessDeniedException: /Users/rpeters/Projects/flex-offers-engine/.metals/readonly/scala/concurrent/duration/Dura
tion.scala######### ] 52 source files formatted
...
```

## Expectation

I would like scalafmt to automatically ignore the `.metals/` directory by default so it does not have to be manually specified.

## Workaround

`scalafmt --exclude .metals/`

**Comment by tanishiking** [comment]
Thank you for reporting! Nice catch 👍 
We might need some more robust solutions for filtering out the unexpected scala sources (than just ignoring a specific directory) so that we can avoid this problem if other tools generate scala sources in other directories.

BTW, `--git` or `project.git` will help you if you add `.metals` in `.gitignore` :)

**Comment by kitbellew** [comment]
consolidated in #1644.
