### ISSUE TITLE
Configuration for keep empty lines at the start of code blocks

### ISSUE THREAD

**Issue by poslegm** [scalameta/scalafmt#1542]
Default behavior was changed in https://github.com/scalameta/scalafmt/pull/1431 and https://github.com/scalameta/scalafmt/pull/1541. 

Now scalafmt removes empty lines at the end and start of code blocks. But empty lines at start of definitions can be used to reduce vertical clamping.

Should we introduce `newlines.keepEmptyLineAtBlockStart` option for keeping them?

**Comment by neko-kai** [comment]
I don't see how this reduces code complexity vs. just keeping `newlines.avoidEmptyLinesAroundBlock` public, especially since the configuration is in the source code anyway because of ediition switching.

**Comment by olafurpg** [comment]
@neko-kai the problem with supporting `N` boolean configuration options is that they can be combined in `2^N` number of ways, of which most combinations have never been tested. An example issue where settings are combined in unexpected ways is https://github.com/scalameta/scalafmt/issues/1539.

**Comment by olafurpg** [comment]
I'm open to partially revert the changes from #1431 so that it only strips closing blank lines while still allowing users to control the opening blank lines, as discussed in https://github.com/scalameta/scalafmt/pull/1541#issuecomment-546910497. However, I'm not sure we should go ahead with that partial revert right away. For now, users can stay on `edition = 2019-10` if they dislike the new change and report feedback in this issue that they are blocked from upgrading to the latest edition.

**Comment by olafurpg** [comment]
The new behavior introduced by #1431 mirrors the formatting behavior in Prettier. From what I've seen, Prettier doesn't have an option to control this specific behavior so I think it would be great if we can avoid it as well.

**Comment by neko-kai** [comment]
@olafurpg 
Why is Prettier related? It may be popular among open source library authors, but e.g. Intellij/WebStorm JavaScript formatter has a large amount of options, as expected.

>  the problem with supporting N boolean configuration options is that they can be combined in 2^N number of ways, of which most combinations have never been tested. An example issue where settings are combined in unexpected ways is #1539.

The alternative is compromising on functionality – the Scala community is plural, with multiple divergent writing styles, the fact that basically everyone tweaks scalafmt's defaults and uncovers these bugs supports that – a less configurable formatter excludes members of the community with styles that aren't replicable by defaults. tbh personally I'd rather see broken combinations – with an opportunity for contributors to fix them if they want to use, rather than a blanket ban on options – that also excludes contributors from adding the options that they do want to use.

**Comment by tanishiking** [comment]
> the Scala community is plural, with multiple divergent writing styles

I understand that. Though Scala has a long history, because of its complexed syntax (in comparison to something like Golang and Python), it's challenging to establish the coding style most of the Scala developers can accept.
However, we want scalafmt to be more conservative about adding new options, for mainly two reasons

- Now, scalafmt has a bunch of options, and it is becoming impossible to infer its behavior under various combinations of options. I don't mean to make scalafmt opinionated, but I want to avoid adding a new option as much as possible if that behavior would be widely acceptable to the community.
- Since scalafmt has a lot of configurable options, users always wonder about which combination of options is the best for them. This situation is going against the intention of code formatter (suppress the discussion over the coding style, and save developer's time).

I understand supporting `newlines.keepEmptyLineAtBlockStart` wouldn't complicate the maintainability of scalafmt so much, but under the thought above, I want to be conservative about adding new options to scalafmt.
To show the importance of this option, we may need some more examples(Scala projects) that prefers this style of coding, and need to see more people's opinion about this option.

---

I just looked around some famous Scala projects (zio, cats, sbt, metals, Scala), and found that some projects prefer to add a new line at the beginning of the block if inside of the block begins with Scaladoc like
- [(from cats)](https://github.com/typelevel/cats/blob/134570b97a3f268cb7d2656ecb4b254c601fc12b/core/src/main/scala/cats/instances/function.scala#L12-L88)
- [(from zio)](https://github.com/zio/zio/blob/8cf038b2b87f44402d304004ace54f0e7e1cedc2/core/shared/src/main/scala/zio/internal/Executor.scala#L28-L83)
- [(from sbt)](https://github.com/sbt/sbt/blob/2f31849c64957592d992a55c71b0bfe393166681/internal/util-collection/src/main/scala/sbt/internal/util/Attributes.scala#L22-L51)
- [(from metals)](https://github.com/scalameta/metals/blob/9eddd91fc831b8b4d185038e18673ebed38f4d52/metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageClient.scala#L16-L26)
- [from scala/scala](https://github.com/scala/scala/blob/b0e1ad01704fe7bace4b236c1cc48fcdbd04b081/src/library/scala/collection/LazyZipOps.scala#L24-L3://github.com/scala/scala/blob/b0e1ad01704fe7bace4b236c1cc48fcdbd04b081/src/library/scala/collection/LazyZipOps.scala#L24-L34).
So, I'm personally leaning toward making this option configurable.

**Comment by olafurpg** [comment]
> I just looked around some famous Scala projects (zio, cats, sbt, metals, Scala), and found that some projects prefer to add a new line at the beginning of the block if inside of the block begins with Scaladoc like

In the case of Metals, we would would not object to using the default in Scalafmt. I think it's best to release the new behavior and collect feedback here to understand better the reasoning why it's undesireable to have the blank lines stripped away.

**Comment by tanishiking** [comment]
>  I think it's best to release the new behavior and collect feedback here to understand better the reasoning why it's undesireable to have the blank lines stripped away.

I agree with that 👍

**Comment by ghostdogpr** [comment]
I just noticed this change after trying to upgrade. My code is full of those empty lines, I use it for keeping the code readable and I think it definitely looks worse without them: everything looks squashed, I feel the code needs to "breathe" a little bit.

To have to use `edition = 2019-10` forever if I don't want this behavior is not very satisfying.

**Comment by adamgfraser** [comment]
Hi. ZIO and Caliban contributor here.

First, thank you for making a great piece of software that we use every day in our software development! 

That being said, I agree with the points @ghostdogpr made above. This is making us not want to upgrade to the latest version, which right now isn't the end of the world but long term is a big negative that we are going to be missing out on future improvements you are making and will fracture the user base across versions. Hopefully we can do something about this.

**Comment by ioleo** [comment]
I also feel like my code needs space to breathe as @ghostdogpr pointed out. I'd love to see an option to configure this.

**Comment by dwijnand** [comment]
Same here.

I prefer

```scala
private[lagom] class AkkaManagementTrigger(
    config: Config,
    system: ActorSystem,
    coordinatedShutdown: CoordinatedShutdown
)(implicit executionContext: ExecutionContext) {

  private val enabledSetting       = "lagom.akka.management.enabled"
  private val enabledRenderedValue = config.getValue(enabledSetting).render()
  private val enabled              = config.getBoolean(enabledSetting)
  
...
   *         retrieve only unseen events
   */
  protected def mapStartingOffset(storedOffset: Offset): AkkaOffset = OffsetAdapter.dslOffsetToOffset(storedOffset)

}
```

to

```scala
private[lagom] class AkkaManagementTrigger(
    config: Config,
    system: ActorSystem,
    coordinatedShutdown: CoordinatedShutdown
)(implicit executionContext: ExecutionContext) {
  private val enabledSetting       = "lagom.akka.management.enabled"
  private val enabledRenderedValue = config.getValue(enabledSetting).render()
  private val enabled              = config.getBoolean(enabledSetting)

...
   *         retrieve only unseen events
   */
  protected def mapStartingOffset(storedOffset: Offset): AkkaOffset = OffsetAdapter.dslOffsetToOffset(storedOffset)
}
```

**Comment by olafurpg** [comment]
Thank you all for the feedback! There's an active discussion in #1546 about how to incorporate "let the code breathe" into the default behavior without introducing a new configuration option.

**Comment by olafurpg** [comment]
I agree that there are cases where it's desirable to leave blank lines in large classes, or before large inner methods, etc. I think it would be great to support this out of the box without forcing users to dig through the website and find the name of the configuration option that lets the code breathe (it's not clear from the name of `newlines.avoidEmptyLinesAroundBlock`)

**Comment by jalaziz** [comment]
> I understand that. Though Scala has a long history, because of its complexed syntax (in comparison to something like Golang and Python), it's challenging to establish the coding style most of the Scala developers can accept.

While this is true, there is a published [official Scala style guide](https://docs.scala-lang.org/style/).

For empty lines in code blocks, it does have a specific recommendation but only when a class has extensions. See #1975 for details.

At the very least, it seems like scalafmt should allow enforcing the official style guide.

I realize it's not full-proof and there's plenty of room for interpretation in some cases, but I was surprised to see scalafmt didn't support some of the recommended styling when switching over.
