### ISSUE TITLE
2.4.0 not available on maven

### ISSUE THREAD

**Issue by adampauls** [scalameta/scalafmt#1664]
Not sure if there's a better way to raise this than a full blown issue: 2.4.0 looks like it's been released, but it won't download and I don't see it in any of the online repositories. I'm eager to try it out! Did something go wrong with publishing, or should I just be patient?

**Comment by olafurpg** [comment]
Thanks for reporting! It looks like the released version is 2.4.0-RC1, see the tag number in https://github.com/scalameta/scalafmt/releases/tag/v2.4.0-RC1

**Comment by kitbellew** [comment]
@adampauls i am a novice "releaser", so, yes, for now it's `-RC1`. i will probably tag `-RC2` in a couple of days, some related commits to be included, and any fixes to the problems the community raises.

**Comment by olafurpg** [comment]
The release notes were great! We can update the title to include RC1 and it might be good to include a short note on what is blocking the 2.4.0 final release.

**Comment by kitbellew** [comment]
@olafurpg i will mention `-RC1` in the title. however, i can't find it on maven either.

**Comment by tanishiking** [comment]
Thank you so much for writing the release note! That's amazing!

I could download 2.4.0-RC1 using scalafmt-cli, and it looks fine https://search.maven.org/artifact/org.scalameta/scalafmt-core_2.13/2.4.0-RC1/jar 👍 
I'm not 100% sure, but the delay might be caused by sonatype (or maybe our release procedure 🤔):  when I tried to release sbt-scalafmt 2.3.1, it took almost one or two days before it is available from sonatype.

**Comment by adampauls** [comment]
Thanks, I was able to download RC1
