### ISSUE TITLE
Inconsistent formatting of if/else

### ISSUE THREAD

**Issue by paulkore** [scalameta/scalafmt#1747]
Version: 2.4.2

```
val a = 5

// 1
val ok1 = if (a > 10) Some(a) else None

// 2
val ok2 = if (a > 10) {
  Some(a)
} else {
  None
}

// 3
val ok3 = if (a > 10)
  Some(a)
else
  None

// 4
val ok4 = if (a > 10) Some(a) else {
  None
}

// examples 1-2 are unaffected

// example 3 is re-written as:
val ko3 =
  if (a > 10)
    Some(a)
  else
    None

// example 4 is re-written as:
val ko4 =
  if (a > 10) Some(a)
  else {
    None
  }

```

It seems that the formatting of examples 3 and 4 is not consistent with example 2; The "if" is pushed to the next line for some reason.

**Comment by kitbellew** [comment]
@paulkore i agree that 2 should be rewritten just like 3, with `if` being pushed to the next line for the same reason.

**Comment by paulkore** [comment]
Thanks, @kitbellew 
I understand that there's currently no way to configure scalafmt to "preserve" the line breaks in if/else blocks ?

**Comment by kitbellew** [comment]
@paulkore i don't think so. and i doubt that the maintainers will allow such granular control in the future.

**Comment by paulkore** [comment]
There seem to be other cases that do offer a "preserve" option, for example "trailingCommas" is either "always", "never", or "preserve"....

Given the above, it seems inconsistent to not allow "preserve" on other things, such as if/else line breaks.

**Comment by tanishiking** [comment]
Pasting my opinion about this from https://github.com/scalameta/scalafmt/pull/1752#issuecomment-593169291

---

Thank you so much for modifying @kitbellew and your comment @paulkore 

IMO, we don't have to fix this "inconsistency" between if/else with and without braces. (I mean it's best to maintain the status quo).

Though @paulkore mentioned that there's an inconsistency between those formatting results, I think we don't have to honor the consistency about the indent/newline between them,
because they have different syntax, and actually (as far as I know) a lot of scala developers prefer to use different coding styles for if/else statement with and without braces.

```scala
// without braces
val ok3 =
  if (a > 10) Some(a)
  else None

// with braces
val ok3 = if (a > 10) {
  Some(a)
} else {
  None
}
```

That's why I believe it's better not to change the current behavior.
It might be better to hear more opinions from other scala developers, I guess.

---

It's ok with adding an option, but in that case, I think it's better to keep the default behavior.

**Comment by kitbellew** [comment]
fixed by
#1778 
#1779

**Comment by paulkore** [comment]
@kitbellew thanks for the update.
I imagine, that this will be included in the next release? Do you know when the release is planned for?
