### ISSUE TITLE
Idempotence violation on argument indent

### ISSUE THREAD

**Issue by poslegm** [scalameta/scalafmt#1804]
This template is a guideline, not a strict requirement.
- **Version**: 2.4.2
- **Integration**: IntelliJ
- **Configuration**:
```
version = 2.4.2
maxColumn = 80
```

## Steps

Unit test fails with idempotence violation

```scala
<<< ONLY idempotence
object a {
  lazy val mod = project(
      "mod",
      Seq(common, db, user, hub, security, game, analyse, evaluation, report))
    .settings(
      libraryDependencies ++= provided(play.api, play.test, RM, PRM)
  )
}
>>>
object a {
  lazy val mod = project(
    "mod",
    Seq(common, db, user, hub, security, game, analyse, evaluation, report)
  ).settings(
    libraryDependencies ++= provided(play.api, play.test, RM, PRM)
  )
}
```

## Notes

May be related to #1802

**Comment by kitbellew** [comment]
@poslegm i looked through the sequence of these bugs, and i am fairly certain most (if not all) of them are due to two different rules for config-style and non-config-style apply in the input. if the non-config-style gets formatted as a config-style, the next time around formatter uses a different rule. the good news is that all subsequent invocations will also use the config-style rule.

merging these two rules without changes in the formatted output might prove to be difficult.
