### ISSUE TITLE
Alignment broken around mix of appends and tuples

### ISSUE THREAD

**Issue by bdarfler** [scalameta/scalafmt#187]
Original:

``` scala
dest     += s"#$i $infix ${if (writeOnce) s"if_not_exists(#$i, :$i)" else s":$i"}"
values   += s":$i" -> toAttrVal(value)
names    += s"#$i" -> field 
```

Scalafmt:

``` scala
dest += s"#$i $infix ${if (writeOnce) s"if_not_exists(#$i, :$i)" else s":$i"}"
values += s":$i" -> toAttrVal(value)
names += s"#$i"  -> field
```

I would like the input to look like this:

``` scala
dest     += s"#$i $infix ${if (writeOnce) s"if_not_exists(#$i, :$i)" else s":$i"}"
values   += s":$i" -> toAttrVal(value)
names    += s"#$i" -> field 
```

Using
- 0.2.1

**Comment by olafurpg** [comment]
I welcome contributions for improvements on vertical alignment, since I don't use the feature myself. I've labeled [all related issues here](https://github.com/olafurpg/scalafmt/issues?q=is%3Aissue+is%3Aopen+label%3Aalignment).

`defaultWithAlign` does not align by `+=`, you'll need to configure it first. The current alignment implementation does not support aligning by a variable number of columns in subsequent rows, it will only align up to the last column that all rows have in common. [This comment](https://github.com/olafurpg/scalafmt/issues/172#issuecomment-211359227) describes  where would best to start.

**Comment by bdarfler** [comment]
Thanks I'll see if I can make some time for this.

**Comment by olafurpg** [comment]
It's possible to align by the `+=` with the following settings
```scala
bash-3.2$ cat .scalafmt.conf
align.tokens = ["+=", "->"]
bash-3.2$ ../scalafmt -c .scalafmt.conf --stdout foo.scala
object foo {
  values += s":$iiii" -> toAttrVal(value)
  names  += s"#$i"    -> field
}
```
Note if there is a third line however that does not contain a `->` then scalafmt will only align the first column and skip the `->` alignment
```scala
bash-3.2$ ../scalafmt -c .scalafmt.conf --stdout foo.scala
object foo {
  keys   += s":$iiiiaaaaaa"
  values += s":$iiii" -> toAttrVal(value)
  names  += s"#$i" -> field
}
```
