### ISSUE TITLE
config-style alignment of named arguments

### ISSUE THREAD

**Issue by poslegm** [scalameta/scalafmt#1921]
This template is a guideline, not a strict requirement.
- **Version**: 2.5.0-RC3
- **Integration**: IntelliJ
- **Configuration**:
```
version = 2.5.0-RC3
align.tokens.add = ["="]
```

## Steps

Given code like this:
```scala
JwtClaim(
  abc = cba,
  content = content
)
```

## Problem

Scalafmt formats code like this:
```scala
JwtClaim(
  abc = cba,
  content = content
)
```

## Expectation

I would like the formatted output to look like this:
```scala
JwtClaim(
  abc     = cba,
  content = content
)
```

## Workaround

It can be achieved with `Term.Assign` owner for `=`: `align.tokens.add = [{code = "=", owner = "(Enumerator.Val|Defn.(Va(l|r)|Def|Type)|Term.Assign)"}]`. But it also align all other assignments:

```scala
val header  = JwtHeader(algorithm = Some(JwtAlgorithm.HMD5))
val claim   = JwtClaim(content    = content)
val content = makePayloadStr(paymentId, userId, template)
```

## Notes

I think that the best solution would be introducing dedicated owner for assigning of named arguments.

**Comment by neko-kai** [comment]
@poslegm 
This affects not just assignments, the same behavior for me applies for `->` in expressions:

```hocon
version = "2.5.0-RC1"
align = most
```

with 2.4.2:

```scala
object fmt {
  for {
    _      <- log.info(s"Parsing unparsed ${files.size -> "files"}...")
    parsed <- F.parTraverse(files)(parseFile)
    _      <- log.info(s"Got ${parsed.size -> "entities"}.")
  } yield ()
}
```

with 2.5.0-RC1

```scala
object fmt {
    for {
      _      <- log.info(s"Parsing unparsed ${files.size -> "files"}...")
      parsed <- F.parTraverse(files)(parseFile)
      _      <- log.info(s"Got ${parsed.size             -> "entities"}.")
    } yield ()
}
```

Also `Term.Assign` covers only applications, for alignment in definitions of default parameters `=`'s `Term.Param` owner is required.

As the bug affects not just assignments (and not just manually added tokens, it's present with `align = most`), ideally maybe there could be a way to fix it for all operators, while avoiding the bugs fixing which caused it, instead of hard-coding a fix for assignment...

**Comment by poslegm** [comment]
Yes, you are right, it is a bug. I will fix it
