### ISSUE TITLE
SearchStateExploded on danglingParentheses.preset=false

### ISSUE THREAD

**Issue by poslegm** [scalameta/scalafmt#2085]
This template is a guideline, not a strict requirement.
- **Version**: 2.6.2
- **Configuration**:
```
version=2.6.2
danglingParentheses.preset=false
```

## Steps

Given code like this:
```scala
class ServiceSpec {
    def gen() =
      g.copy(context =
        g.context.copy(
          price = g.context.price.copy(
            price = g.context.price.price.copy(
              prolongPrice = prolongPrice,
              modifier = Some(m.copy(changed = removed))))))
}
```

When I run scalafmt like this:

```bash
scalafmt
```

## Problem

```
org.scalafmt.cli.FailedToFormat: /private/tmp/a.scala
Caused by: org.scalafmt.Error$SearchStateExploded: Search state exploded on 'price∙=[197:199]', line 6
        at org.scalafmt.internal.BestFirstSearch.shortestPath(BestFirstSearch.scala:188)
```

## Workaround

Enable danglingParentheses or extract `Some(m.copy(changed = removed))` to variable

**Comment by kitbellew** [comment]
@poslegm another workaround is increasing `runner.optimizer.maxVisitsPerToken`. should we just increase the default?

honestly, i am not even sure why it was set so low; we changed our limit from 512 to 50000, and time to format several thousand files didn't seem to change, because such complex cases appear very rarely.
