### ISSUE TITLE
How to ignore completely user's style 

### ISSUE THREAD

**Issue by ghostbuster91** [scalameta/scalafmt#2348]
Hi,

Maybe it is not a bug but rather a question about particular switch in the configuration but I couldn't find it. 
I am not sure if there is/should be a single switch for that or these are/should be two different options.

# 1. force single line whenever possible
```
version = 2.7.5
maxColumn = 100
```

### Steps

Given code like this:
```scala
method(
      Seq(
        param1,
        param2
      ),
      date
)
```

When I run scalafmt like this:

```bash
scalafmt
```

### Problem

Scalafmt formats code like this:
```scala
method(
      Seq(
        param1,
        param2
      ),
      date
)
```

### Expectation

I would like the formatted output to look like this:
```scala
loadProducts(Seq(product1, product2), date)
```

If I format the code manually to
```scala
loadProducts(Seq(product1, product2), date)
```
scalafmt keeps that formatting. 

## 2. always break the chains
```
version = 2.7.5
maxColumn = 100
```

### Steps

Given code like this:
```scala
 val p1 = p2.withId("12345").withValues(Seq("223456789"))
```

When I run scalafmt like this:

```bash
scalafmt
```

### Problem

Scalafmt formats code like this:
```scala
 val p1 = p2.withId("12345").withValues(Seq("223456789"))
```

### Expectation

I would like the formatted output to look like this:
```scala
 val p1 = p2
   .withId("12345")
   .withValues(Seq("223456789"))
```

**Comment by ghostbuster91** [comment]
@kitbellew As I said `I couldn't find it.`

I would really appreciate it if you could point me to some direction rather than closing the issue with such meaningless reply. 
Simply saying which of them is possible and why the other isn't would be great.

**Comment by tgodzik** [comment]
@ghostbuster91 Please do keep the comments civil, there is no reason for negative responses such as above. Short answers do not mean that maintainers ignore you, but rather might be short on time. Instead of:
`I would really appreciate it if you could point me to some direction rather than closing the issue with such meaningless reply.`
it would be enough to write:
`I can't find the exact configuration options, could you point me to them?`   

As this is an open source project maintainers are in no way obliged to answer you and if they do they often do it in their free time. Being as polite as possible makes their work easier and increases the possibility that you will actually get the answer you seek.

From what I checked on the configuration page these options might interest you:
- https://scalameta.org/scalafmt/docs/configuration.html#optinbreaksinsidechains
- https://scalameta.org/scalafmt/docs/configuration.html#newlinessource

Not sure if any of them exactly suite your needs, but you would need to experiment yourself.

**Comment by ghostbuster91** [comment]
@tgodzik Thanks for the reply. First let me say that, I didn't want to sound rude under no circumstances, I am truly sorry if my response sounded in that way. 

I know how oss works, I obviously I try to respect maintainers time. I wouldn't even start that topic without first trying to find these configurations by myself. I also tried to provide the most meaningful and concise description of my problem and I wouldn't mind waiting longer to get a little bit more detailed answer. At the beginning of that issue I stated that it might be a question about an existing configuration option, which to me implies that I couldn't find it, if it existed. 


I run across `optinbreaksinsidechains` but it isn't what I am looking for, because it just breaks the chain or not depending on existence of line break after first dot. 

`newlinessource` seems like something I was looking for. I will give it a try, thanks!

**Comment by kitbellew** [comment]
@tgodzik thanks for the help!

@ghostbuster91 i understand how you feel. you took a more popular approach the second time, when you asked fellow users on gitter, that's how they usually do it.

but generally, people put a lot of effort to document many configuration options; instead of searching (by what?), those users who could answer you simply read through the document from the beginning to the end and would have seen description and examples of the desired behavior.

definitely more effort, but, as they used to say during the times of henryk senkiewich, rtfm.
