### ISSUE TITLE
How should I start the creation of a new rule?

### ISSUE THREAD

**Issue by siers** [scalameta/scalafmt#2350]
I want to develop a new rule. How do I start?

How do I load the correct environment to import and try out scala.meta's parsers in the REPL?
How do I run only a single rule's *.stats/test files?
Is there anything other than `tests/test` that would come in handy?

**Comment by tgodzik** [comment]
> How do I load the correct environment to import and try out scala.meta's parsers in the REPL?

You should be able to just run `sbt console` and then `import scala.meta._`, which would allow you to just do "code".parse. You can see some actual code examples here: https://github.com/tgodzik/scala3-compiler-interactions/blob/main/scalameta/src/main/scala/parser/scalameta/Parser.scala

> How do I run only a single rule's *.stats/test files?

You can just run in sbt `~tests/testOnly org.scalafmt.FormatTests -- *OpaqueType.stat*`, which will run a single stat file matched by the second expression after `--` or add `ONLY` to specific test case you want to run

> Is there anything other than tests/test that would come in handy?

Most of the times I just run the above and was able to fix any issues.

Please do create an issue about an issue you might want to create, so that we could add some feedback on whether it is plausible and where to look.

**Comment by siers** [comment]
Thank you!
