### ISSUE TITLE
Please support a 4-space indent.

### ISSUE THREAD

**Issue by soshiharami** [scalameta/scalafmt#2385]
## Problem

Why does this formatter not support 4-space indentation?
I know that 2-space is widely known in the scala community, as talked about in a past issue ( #1493 ), but I think there are many engineers who want to use 4-space.
Are there any technical difficulties?

## Expectation

support a 4-space indent.

**Comment by tgodzik** [comment]
This was previously closed due to the fact that 2-space indentation is accepted as the default for Scala codebases. I think we might revisit this with the Scala 3 optional braces around the corner. What do you think @olafurpg @kitbellew ?

**Comment by olafurpg** [comment]
Configurable indentation could actually cause more problems for Scala 3 compared to Scala 2. If different codebases use different indentation width then it will be more likely that users hit on issues when copy pasting code.

**Comment by tgodzik** [comment]
Though, that is still possible without scalafmt and having that as an option would mean people need to just copy and paste it then run scalafmt. We might need to also provide better support for pasting in IDEs.

I am mostly raising it, because I think the general consensus in the thread about optional braces was: `scalafmt will handle that` :sweat_smile:

**Comment by soshiharami** [comment]
Thanks for the quick response.
For example, how about implementing it with a simple warning like dangerous or not recommended options?
This way, the code style of the whole community will be preserved and only those who want to use it will be able to do so.

**Comment by kitbellew** [comment]
> This was previously closed due to the fact that 2-space indentation is accepted as the default for Scala codebases. I think we might revisit this with the Scala 3 optional braces around the corner. What do you think @olafurpg @kitbellew ?

@tgodzik why would blocks without braces require a different level of indentation?

**Comment by tgodzik** [comment]
There was a whole discussion about it on the contributors thread, which was super long. Generally people felt like two spaces are not enough to distinguish different levels and figured 3 spaces would do the trick. That one was Martin's conclusion. And the consensus was that tooling (scalafmt) would be just used to set the proper indentation. I am fine with leaving 2, but I think people will start raising issues about it.

**Comment by kitbellew** [comment]
> There was a whole discussion about it on the contributors thread, which was super long. Generally people felt like two spaces are not enough to distinguish different levels and figured 3 spaces would do the trick. That one was Martin's conclusion. And the consensus was that tooling (scalafmt) would be just used to set the proper indentation. I am fine with leaving 2, but I think people will start raising issues about it.

Weeeeeell... if Martin said it... should we then just have a parameter specifically for indentation of scala3 blocks when braces are omitted?

**Comment by tgodzik** [comment]
I was also thinking about that one. Maybe just set it to 3 by default?

**Comment by kitbellew** [comment]
> I was also thinking about that one. Maybe just set it to 3 by default?

_that_ will work!

**Comment by olafurpg** [comment]
The significant indentation behavior for Scala 3 will need a proper discussion in a separate issue. With significant indentation I think it’s even more important than before that Scalafmt only supports a single indentation style so that copy-pasting between projects works. I have seen first-hand how inconsistent indentation conventions can cause problems for Python beginners who are trying to adjust online code examples into their project.

**Comment by kitbellew** [comment]
> I have seen first-hand how inconsistent indentation conventions can cause problems for Python beginners who are trying to adjust online code examples into their project.

@olafurpg if there's an online code example, what happens when the user pastes it into this ide? the whole snippet preserves its indentation but might be off relative to surrounding code? how would standardizing offset mitigate this?

I'm a big proponent of standardization (which includes indents, line lengths, etc), but it did take me a minute to get used to 2 (longer than the switch from 8 to 4 earlier), and since people are making it into such an issue, wanted to understand.
