### ISSUE TITLE
When use 'verticalMultiline.atDefnSite' with 'align.openParenDefnSite'...

### ISSUE THREAD

**Issue by ssosso** [scalameta/scalafmt#3252]
## Configuration (required) ##

Please paste the contents of your `.scalafmt.conf` file here:
```
maxColumn = 80
indent.defnSite = 2
verticalMultiline = {
    atDefnSite = true
    arityThreshold = 2
    newlineAfterOpenParen = false
}
align.closeParenSite = true
align.openParenDefnSite = true
...
```

## Command-line parameters (required) ##

When I run scalafmt via CLI like this: `scalafmt {fileName}.scala`

## Steps

Given code like this:
```scala
def other(a: Int, b: Double)(c: String) = a + b + c
```

## Problem

Scalafmt formats code like this:
```scala
def other(
  a: Int,
  b: Double
)(c: String
) = a + b + c
```

## Expectation

I would like the formatted output to look like this:
```scala
def other(a: Int, // align by (
          b: Double
         )(c: String
         ) = a + b + c
```

## Workaround

I also tried changing the order of the configurations, but it didn't work.

## Notes

I know that this issue is not problem. Because I see the docs of scalafmt and docs tell me that this is right. 
But.. I want my code to be formatted like 'Expectation'

**I want to set configuration about newline for the first open paren in the definition section and set about aligning accordingly. 
I am preparing an improvement PR in scalafmt's code.. BUT First of all, I want to know why verticalMultiline unconditionally breaks After the first open paren.**

**Comment by kitbellew** [comment]
vertical multiline is a special form which doesn't allow alignment. its requirements are: one param per line; all parameters have the same indentation. in your case, second param group has a different indentation from the first. and the first parameter is not by itself.

**Comment by kitbellew** [comment]
> Scalafmt formats code like this:
> 
> ```scala
> def other(
>   a: Int,
>   b: Double
> )(c: String
> ) = a + b + c
> ```

Are you sure it's not:
```scala
def other(
  a: Int,
  b: Double
)(
  c: String
) = a + b + c
```

**Comment by ssosso** [comment]
@kitbellew 
Thanks for your reply.

Because second param group was influenced by `verticalMultiline.newlineAfterOpenParen = false`, there isn't a newline after the open paren of second param group.

So it's right like this:
```scala
def other(
  a: Int,
  b: Double
)(c: String
) = a + b + c
```


Well.. I'd like to be able to have one parameter per one line, along with aligning with open paren for first parameter group.
Is it impossible to format in the form below with the combination of existing configurations?
```scala
def other(a: Int, // align by (
          b: Double
         )(c: String
         ) = a + b + c
```

After all.. is it possible only when new features are added to Scalafmt?
Do you have any ideas for me if it's only possible by implementing it as a new feature?
If you help me, I will try to add a new function based on your help.

**Comment by kitbellew** [comment]
the short answer is no, it's not possible.

vertical multiline rules are implemented so that there's absolutely no choice in how it's formatted. choice equals complexity, and the single most complex set of rules today is one which formats stuff between parentheses of a definition or method call.

note how the parameter you use, newlineAfterOpenParen, is not used for the first parameter group; the same reason -- avoid complexity. and aligned indent for the first group, since it depends on the length of the method name and the lengths of each parameter signature, will frequently overflow the line and thus require a choice -- to break, like today. that choice is hard to implement.

I'll close this request, but you can try another parameter, newlines.beforeOpenParenDefnSite, instead of vertical multiline, perhaps it will be closer to what you want.
