### ISSUE TITLE
False positive error code of scalafmt cli upon parser error

### ISSUE THREAD

**Issue by WojciechMazur** [scalameta/scalafmt#3354]
In case of getting a parser error, CLI would return an exit value of 0, even though the program finished with an error. Because of the false positive result scripts used in the CI are not aware of scalafmt --test failure. 

## Configuration (required) ##

Please paste the contents of your `.scalafmt.conf` file here:
```
version = 3.6.0
runner.dialect = scala3
```

## Command-line parameters (required) ##

Given code like this in file test.scala:
```scala
#!/usr//env -S scala-cli shebang

@main def foo() = println("Hello")```
```

Running: 
```bash 
scalafmt --test test.scala
echo $?
```

## Problem

Output: 
```
> ✗ scalafmt --test scripts
org.scalafmt.dynamic.exceptions.PositionExceptionImpl: test.scala:1: error: [dialect scala3] illegal start of definition identifier
#!/usr//env -S scala-cli shebang
^: test.scala
error: ParseError=2

>  echo $?
0
```

## Expectation
Error code 2 should be propagated and returned from cli to make it usable in the CI process.

**Comment by kitbellew** [comment]
@WojciechMazur the issue template probably asked you to try an updated version of the cli, which you skipped.

what is the version of scalafmt that you're running? (since it's a dynamic exception, it's not 3.6.0.) I'd like you to try both 3.5.9 and 3.6.0.

p.s. I'm not talking about the version mentioned in the configuration file.

**Comment by kitbellew** [comment]
discussed this same problem with @ekrich on discord. closing.
