### ISSUE TITLE
scalafmt says there is things to format in Windows but not in macos/ununtu

### ISSUE THREAD

**Issue by pathikrit** [scalameta/scalafmt#3462]
## Configuration (required) ##

Please paste the contents of your `.scalafmt.conf` file here:
```
maxColumn = 140
align.preset = more
version = 3.7.1
project.layout = StandardConvention
runner.dialect = scala213source3
docstrings.style = keep
```

I tried to matrix build better-files across Windows, OSX and Ubuntu here:
https://github.com/pathikrit/better-files/actions/runs/4157369757/jobs/7191823009

The windows one failed with "needed formatting" error

**Comment by kitbellew** [comment]
Unfortunately, it's a bit hard to know what the issue is about.

1. you have not provided explicit, reproducible examples here; while we appreciate the github link, it doesn't make it reproducible.
2. you are using `sbt` and not the `scalafmt` binary, as the issue submission template requests.

my only guess is that the git command on Windows checks out using CRLF and the formatter by default formats using LF.
