### ISSUE TITLE
java.lang.IllegalArgumentException: Cannot add dependency 

### ISSUE THREAD

**Issue by johnynek** [scalameta/scalafmt#414]
`scalafmtTest` and `scalafmt` fail to run for me using this PR:
https://github.com/twitter/scalding/pull/1588

I tried to follow the instructions, but I am working with a build file that is 4.5 years old in some form and I am really not an sbt expert (though the build seems to work for all the other plugins we have).

**Version**: 0.3.1
**Integration**: sbt
**Configuration**: see: https://github.com/twitter/scalding/pull/1588

**Comment by johnynek** [comment]
probably the same issue as: https://github.com/ensime/ensime-sbt/issues/210

**Comment by olafurpg** [comment]
Yet another issue caused by the fact that SBT plugins must be 2.10 and scalafmt is 2.11 only ... 😞 (cc/ https://github.com/scalameta/scalameta/issues/295). Similar to the Ensime plugin, scalafmt adds dependencies to the `scalafmt` configuration (like `... % "scalafmt"`) in order classload a 2.11 universe.

Unfortunately, I don't see a way to change the scalafmt plugin until SBT 1.0 adds support for plugins written in 2.11. Until then, https://github.com/twitter/scalding/pull/1571.

**Comment by olafurpg** [comment]
sbt-scalafmt no longer supports sbt 0.13 because of problems like this. To use scalafmt on sbt 0.13 it's possible to use https://github.com/lucidsoftware/neo-sbt-scalafmt or try this workaround http://scalameta.org/scalafmt/#sbt0.13
