### ISSUE TITLE
Integration with intelij - switch menu

### ISSUE THREAD

**Issue by mmatloka** [scalameta/scalafmt#419]
**Version**: 0.3.1
**Integration**: intellij

Hi,
I am wondering about style of integration with intelij. I have used before the intelij Eclipse Code Formatter plugin (it adds feature of code formatting according to eclipse .xml). It makes the swiching between formatters easy, because it adds a position to Switch... menu (win/lin ctrl+backquote) (same menu where you can change color scheme, keymap etc). So just control+backquote  -> "switch code formatter" and you can use standard keyboard shortcuts for formatting. Maybe it would be also an option for scalafmt?

**Comment by olafurpg** [comment]
I agree that it would be nice if IntelliJ plugin could use the standard shortcut for code formatting. That way, scalafmt would integrate better with other IntelliJ features like "Switch ...", etc.

The only reason I didn't do that is because 1) it hasn't bugged me enough and 2) it was quicker/easier to do an action that read/writes the active document. The IntelliJ plugin development docs on adding a code formatter go into PSI elements and other stuff that I didn't want to get into.

If you are interested in taking a shot at this, I happy to review PRs to the IntelliJ plugin. However, it might be more convenient for you to do it after I merge the `intellij` project into the SBT build using https://github.com/dancingrobot84/sbt-idea-plugin It's been on my TODO for a while (#399) but I'm still not sure when I will get to it.

**Comment by olafurpg** [comment]
There's an open youtrack issue about adding builtin support for scalafmt in the IntelliJ Scala plugin https://youtrack.jetbrains.com/issue/SCL-13658

**Comment by olafurpg** [comment]
Superseded by https://youtrack.jetbrains.com/issue/SCL-13658

The functionality of the current Scalafmt IntelliJ plugin will likely remain unchanged unless someone wants to contribute improvements. The long-term solution would be to have built-in support for scalafmt in the IntelliJ Scala plugin.

**Comment by olafurpg** [comment]
The latest IntelliJ Scala EAP has builtin Scalafmt, please give it a try to see if it works as you expect it to :)

![screen shot 2018-07-16 at 16 58 45](https://user-images.githubusercontent.com/1408093/42767988-9f753218-891e-11e8-9317-b04c31d11ce3.png)
