### ISSUE TITLE
IntelliJ plugin: Undo after formatting undoes too much

### ISSUE THREAD

**Issue by andrewkerr9000** [scalameta/scalafmt#442]
Seems to be a bug in the plugin code, not the formatter.

**Version**: (for example, 0.3.1)
0.3.1
**Integration**: (for example, intellij, sbt, library)
IntelliJ
**Configuration**: (for example, `--maxColumn 120`)

```
--style defaultWithAlign
--maxColumn 120
--assumeStandardLibraryStripMargin true
```

(but probably irrelevant)

Steps to reproduce:
Open a scala file
Type `// foo` on a blank line
Format with scalafmt plugin
undo

Expected: Formatting undone, `// foo` still present
Actual: Formatting is undone, and the `foo` in `// foo` is too, leaving only `//`

Undoing IntelliJ's built in formatting works as expected.

**Comment by olafurpg** [comment]
Hmmm. I'm unable to reproduce this issue. 

Is the file properly formatted before you run scalafmt? I think the plugin doesn't do anything if the file is unchanged. Otherwise, the scalafmt intellij plugin using the standard intellij transparent undo action which takes care of handling how undo works: https://github.com/olafurpg/scalafmt/blob/master/intellij/src/org/scalafmt/intellij/ScalafmtAction.scala#L73

I'm not sure what the best way to re

**Comment by andrewkerr9000** [comment]
Still happening with 0.4.5.

I only see this behaviour when scalafmt changes a file.

```
IntelliJ IDEA 2016.2.4
Build #IC-162.2032.8, built on September 9, 2016
JRE: 1.8.0_112-release-b343 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
```

**Comment by olafurpg** [comment]
I use the IntelliJ plugin every day and I have never encountered this. It's impossible for me fix the issue when I can't reproduce it. I'd be interested to know if someone else has also bumped into this.

**Comment by olafurpg** [comment]
I'm unable to reproduce, please reopen if this continues to be a problem.
