### ISSUE TITLE
Can config style at call style sort of bypass select chains?

### ISSUE THREAD

**Issue by sjrd** [scalameta/scalafmt#497]
**Version**: 0.4.3
**Integration**: sbt
**Configuration**: `style = Scala.js`, `maxColumn = 80`

``` scala
  def apply(
      childList: Boolean = false,
      attributes: Boolean = false,
      characterData: Boolean = false,
      subtree: Boolean = false,
      attributeOldValue: Boolean = false,
      characterDataOldValue: Boolean = false,
      attributeFilter: js.UndefOr[js.Array[String]] = js.undefined
  ): MutationObserverInit = {
    val res = js.Dynamic.literal(
        "childList" -> childList,
        "attributes" -> attributes,
        "characterData" -> characterData,
        "subtree" -> subtree,
        "attributeOldValue" -> attributeOldValue,
        "characterDataOldValue" -> characterDataOldValue
    ).asInstanceOf[MutationObserverInit]
    attributeFilter.foreach(res.attributeFilter = _)
    res
  }
```

Scalafmt:

``` scala
  def apply(
      childList: Boolean = false,
      attributes: Boolean = false,
      characterData: Boolean = false,
      subtree: Boolean = false,
      attributeOldValue: Boolean = false,
      characterDataOldValue: Boolean = false,
      attributeFilter: js.UndefOr[js.Array[String]] = js.undefined
  ): MutationObserverInit = {
    val res = js.Dynamic
      .literal(
          "childList" -> childList,
          "attributes" -> attributes,
          "characterData" -> characterData,
          "subtree" -> subtree,
          "attributeOldValue" -> attributeOldValue,
          "characterDataOldValue" -> characterDataOldValue
      )
      .asInstanceOf[MutationObserverInit]
    attributeFilter.foreach(res.attributeFilter = _)
    res
  }
```

I would like the input to look like the original.

In some sense, I want config style call site to bypass the select chain. I am not sure whether this can be rationalized in a general way (and not specific to `js.Dynamic` somehow). If it cannot, I'll live with the current output of scalafmt. I don't care enough about it.

**Comment by olafurpg** [comment]
Hmmm. We can let config style bypass select chains but I'm not convinced it's worth the effort.

If we want this to apply for any config application in the chain I estimate it might require a bit of changes to the current handling of select chains.

However, it might be easy to allow only the first config application to bypass the select chain. This comes with the requirement that the config application must to be the first method call in the chain (which is the case of `js.Dynamic` in this example). This is because the first method call in the chain determines if the entire chain breaks or not (see bullet no. 2 in [this explanation](https://github.com/olafurpg/scalafmt/issues/444#issue-177591219)).

If this is not a blocker then I'm tempted to close as wontfix. I wouldn't be surprised if there are higher priority issues with the Scala.js style.

**Comment by sjrd** [comment]
That's what I thought. There probably are more important issues ;) Feel free to close or tag with LowPrio or whatever's your way of dealing with stuff like that.

**Comment by olafurpg** [comment]
Cool. Wishlist it is then.
