### ISSUE TITLE
[Feature Request] Auto-sort imports (statements)

### ISSUE THREAD

**Issue by pjrt** [scalameta/scalafmt#722]
We currently have a `SortImports` rewrite, but all it does is sort imports in import groups, it does not sort import statements themselves. 

This:
```scala
import com.comp.A
import com.comp.module.B
import scala.collection.mutable
import scala.util
import scalaz.Functor
import java.time.Instant
```

Would be formatted as:
```scala
import java.time.Instant

import scala.collection.mutable
import scala.util

import scalaz.Functor

import com.comp.A
import com.comp.module.B
```

The order is:
* Java stuff
* scala stuff
* 3rd party stuff
* company stuff
   * This would need some setting specifying what the company domain is: `companyDomain = com.comp`

3rd party stuff can be determined by whether it matches anything else. If it isn't Java, Scala or companyDomain, then it is 3rd party. 

I think we can just expand `SortImports` to handle this. We could check if the `companyDomain` setting is set. If so, expand the sorting. Otherwise do what it currently does.

**Comment by diego-alvarez-hs** [comment]
could we also choose the order of import sections?
As in my company we use a different order:

Something similar to intellij:
![image](https://cloud.githubusercontent.com/assets/12563308/22759938/22547cfa-ee09-11e6-830b-1240501ed516.png)

**Comment by pjrt** [comment]
I've never seen that style. Is that the default style in IntelliJ?

**Comment by diego-alvarez-hs** [comment]
I have no idea, my main editor is Emacs, I don't think that's the default though

**Comment by olafurpg** [comment]
Sorting imports requires semantic information to be 100% accurate, since
Scala allows relative imports. If we were to add this rewrite, I suggest to
include it in the SortImports rewrite with an assumeNoRelativeImports
option enabled.

I recently implemented an organize imports rewrite in scalafix. It removes
unused imports. Handles relative imports. Grouping and ordering is
configurable. I think we can reuse almost everything from that except the
semantic features.


On Wed, 8 Feb 2017 at 23:09, Pedro J Rodriguez Tavarez <
notifications@github.com> wrote:

We currently have a SortImports rewrite, but all it does is sort imports in
import groups, it does not sort import statements themselves.

This:

import com.comp.Aimport com.comp.module.Bimport
scala.collection.mutableimport scala.utilimport scalaz.Functorimport
java.time.Instant

Would be formatted as:

import java.time.Instant
import scala.collection.mutableimport scala.util
import scalaz.Functor
import com.comp.Aimport com.comp.module.B

The order is:

   - Java stuff
   - scala stuff
   - 3rd party stuff
   - company stuff
   ** This would need some setting specifying what the company domain
is: companyDomain
   = com.comp

3rd party stuff can be determined by whether it matches anything else. If
it isn't Java, Scala or companyDomain, then it is 3rd party.

I think we can just expand SortImports to handle this. We could check if
the companyDomain setting is set. If so, expand the sorting. Otherwise do
what it currently does.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/olafurpg/scalafmt/issues/722>, or mute the thread

**Comment by pjrt** [comment]
Oh I forgot to make a mention about relative imports. I actually expected this to be a local thing. If you have a set of imports that isn't at the top, those will get sorted, but that's it, not merging at the top or anything.

**Comment by olafurpg** [comment]
The scalafix implementation only handles global imports, it leaves locally
scoped imports alone.

**Comment by olafurpg** [comment]
For context, here's the link to OrganizeImports in scalafix: https://github.com/scalacenter/scalafix/blob/master/core/src/main/scala/scalafix/util/OrganizeImports.scala
Test suite:
https://github.com/scalacenter/scalafix/blob/master/scalafix-nsc/src/test/resources/syntactic/OrganizeImportsBase.source
https://github.com/scalacenter/scalafix/blob/master/scalafix-nsc/src/test/resources/syntactic/OrganizeImportsRemoveUnused.source
https://github.com/scalacenter/scalafix/blob/master/scalafix-nsc/src/test/resources/syntactic/OrganizeImportsGroupByPrefix.source
https://github.com/scalacenter/scalafix/blob/master/scalafix-nsc/src/test/resources/syntactic/OrganizeImportsExpandRelative.source

**Comment by fommil** [comment]
FYI ensime supports this via scala-refactoring and this kind of config is supported https://github.com/ensime/ensime-server/blob/2.0/core/src/main/resources/application.conf#L5

```
["java", "scala", "akka,play", "*", "com.my.company"]
```

**Comment by olafurpg** [comment]
See https://github.com/scalameta/scalafmt/pull/1038#issuecomment-328357433 for why I am against adding this feature, even behind an `assumoNoRelativeImports = true` setting.

**Comment by olafurpg** [comment]
Gonna close this as won't fix. Scalafmt is a syntactic tool and sorting imports requires semantic information. This feature is better suited for a tool like scalafix, once https://github.com/scalacenter/scalafix/issues/502 is fixed. The problem goes beyond relative imports, shadowing may change by reordering wildcard imports. Running scalafmt should always be a safe operation, and adding this feature even under "assumeNoRelativeImports=true` risks that invariant.
