### ISSUE TITLE
Document <value> in usage/examples better

### ISSUE THREAD

**Issue by dwijnand** [scalameta/scalafmt#757]
- **Version**: 0.5.5
- **Integration**: CLI
- **Configuration**: none

## Steps

After inspecting the usage and examples in `--help` I ran

```bash
scalafmt --stdin --assume-filename build.sbt
```

## Problem

Scalafmt just hung, waiting for input. It didn't show me my `build.sbt` file formatted.

## Expectation

I'm just starting to learn Scalafmt, so my expectation might be wrong. But given I had specified build.sbt I had assumed I had satisfied the need to provide an input.

## Workaround

```bash
scalafmt --stdin --assume-filename build.sbt < build.sbt
```

## Notes

The steps/problem/expectation above were my real user story.

But I believe the underlying issue (thus the issue description) is that the usage doesn't describe what the various `<value>` mean.

For `--config-str <value>     configuration defined as a string` I think it's quite clear.

But for `-f, --files <value>      file or directory, in which case all *.scala files are formatted.` it's starting to get less clear (possibly).

But with `--assume-filename <value> required to format .sbt files with --stdin flag.` I have no idea what to pass as `<value>`.

I'm not sure about the workaround, having to pass build.sbt twice.

**Comment by olafurpg** [comment]
Thank you for reporting! I agree that the cli `--help` message could improve from providing more precise names for `<value>`. Looking at the scopt docs, it seems it's possible to pass a custom `valueName` https://github.com/scopt/scopt#immutable-parsing 

For this example here

```
scalafmt --stdin --assume-filename foo.sbt # required to format .sbt files
```

I think it might be better to include the pipe

```
scalafmt --stdin --assume-filename foo.sbt < foo.sbt # required to format .sbt files
```

> I'm not sure about the workaround, having to pass build.sbt twice.

You can skip `--stdin` and do `-f foo.sbt`. The `--assume-filename` exists because some editor integrations like for vim need to get the code input via stdin and in those cases the cli doesn't know the file extension to pick the correct scala.meta dialect.

**Comment by olafurpg** [comment]
If someone is interested in taking a swing at this, a good place to start looking would be here https://github.com/olafurpg/scalafmt/blob/ee52411bef096d1ae30add30b7c5f9eafebb5fc9/cli/src/main/scala/org/scalafmt/cli/CliArgParser.scala#L18-L32

**Comment by dwijnand** [comment]
Oooooh. So "--assume-filename" actually means "derive the Scala dialect from this filename".

Something that makes that more clear should be a part of fixing this issue, imho.
