### ISSUE TITLE
Handle compressed command-line options

### ISSUE THREAD

**Issue by dwijnand** [scalameta/scalafmt#758]
This template is a guideline, not a strict requirement.
- **Version**: 0.5.5
- **Integration**: CLI
- **Configuration**: none

## Steps

```bash
scalafmt -if build.sbt
```

## Problem

```
Error: Unknown option -f
Error: Unknown argument 'build.sbt'
Try  for more information.
Exception in thread "main" org.scalafmt.Error$UnableToParseCliOptions$: Failed to parse CLI options
	at org.scalafmt.Error$UnableToParseCliOptions$.<clinit>(Error.scala)
	at org.scalafmt.cli.Cli$.mainWithOptions(Cli.scala:64)
	at org.scalafmt.cli.Cli$.main(Cli.scala:58)
	at org.scalafmt.cli.Cli.main(Cli.scala)
```

## Expectation

It would format build.sbt in-place.

## Workaround

```bash
scalafmt -i -f build.sbt
```

**Comment by olafurpg** [comment]
Thanks for reporting! I agree this would be a nice improvement to the cli. I don't think scopt supports compressed options, do you know of any Scala cli arg parser library that does this?

**Comment by dwijnand** [comment]
No, I've never got into that game. But I hear good things about scala-optparse-applicative.

**Comment by olafurpg** [comment]
I'm gonna put the "wishlist" label on this issue, since I don't suspect I will work on it myself. If someone is interested in contributing this feature, I'm happy to help out. I am open for using an alternative library than scopt for command-line arg parsing, but the new implementation would need to be backwards compatible with the current command-line flag syntax.

**Comment by olafurpg** [comment]
Please reopen if someone would like to take a stab at this.
