### ISSUE TITLE
More tests for defaultWithAlign + IntelliJ styles

### ISSUE THREAD

**Issue by dwijnand** [scalameta/scalafmt#810]
- **Version**: N/A
- **Integration**: N/A
- **Configuration**:
```
style = defaultWithAlign
```

## Steps

1. Look up configurations in https://olafurpg.github.io/scalafmt/#Configuration

## Problem

As a strong believer of vertical alignment, and therefore a user of `defaultWithAlign`, what defaults are _for me_ aren't documented.

Instead I'm presented with the default values for the style `default`.

## Expectation

All the non-experimental, out-the-box styles, so currently `defaultWithAlign` and `IntelliJ`, have equal citizenship with the `default` style.

## Workaround

Bookmark https://github.com/olafurpg/scalafmt/blob/master/core/src/main/scala/org/scalafmt/config/Settings.scala so you can reverse-engineer it when you need to.

## Notes

The tyranny doesn't end with just the configuration. `default` is also much more tested and more stable, while `defaultWithAlign`, and I expect `IntelliJ`, suffers from less testing.

**Comment by olafurpg** [comment]
I admit, I don't use defaultWithAlign.

> Instead I'm presented with the default values for the style default.

`defaultWithAlign` has the same default values as `default` except for `align.tokens` (`align.mixedOwners` is not relevant for default, it could be true in default). `align.tokens` is intentionally not documented because

1. the "owner" field in the configuration relies on knowing classnames of scala.meta names,
1. the way it works is not always intuitive. For example, adding more align.tokens (esp. `,` or `:`) may actually decrease the amount of vertical alignment.

> The tyranny doesn't end with just the configuration. default is also much more tested and more stable, while defaultWithAlign, and I expect IntelliJ, suffers from less testing.

I totally agree. I especially want to test all provided styles in the property tests on the big corpus. The current code for the property tests is really and I've wanted to replace it with scalameta-testkit.

**Comment by olafurpg** [comment]
With #964, defaultWithAlign is no longer advertised as a default style, it is replaced with the `align = true` setting. There are also a bit more docs, although they could still be more detailed. If you find a bug in `style=intellij` or `align=true`, please open an issue.
