### ISSUE TITLE
Use HOCON properly

### ISSUE THREAD

**Issue by dwijnand** [scalameta/scalafmt#811]
While I don't think that, necessarily, the way that HOCON does things is the end-all be-all of configuration management, I do think that the some of the issues I've been having with Scalafmt's configuration could've been avoided if HOCON were used properly.

Specifically:

+ using a reference.conf file to define the (base) defaults
+ using include files for the style overlays
+ resolving the configuration before reading from it
+ using += instead of inventing align.tokens.add

**Comment by dwijnand** [comment]
Please let me know if you're interested in this issue, because I might be able to show a prototype or a wip of how I would do this.

**Comment by olafurpg** [comment]
I am not convinced this is a good idea. I want configuration to be a dumb data structure, and I don't want to reason across multiple files to understand what's happening in .scalafmt.conf. Note that scalafmt needs to resolve configuration from several integrations such as intellij/sbt/cli which all invoke the tool from different working directories. 

However, I'm willing to admit that the current setup is suboptimal for power-users who configure a lot. My view is that if you are configuring too many fields, maybe we need to provide better defaults or more base styles. There was a related discussion in #730. 

There is currently no reference.conf because the default settings are defined in scala code as default parameter values, see  https://github.com/olafurpg/scalafmt/blob/1c1d46f3a0eeb154801ca75e8011e78e7fd70eb4/core/src/main/scala/org/scalafmt/config/ScalafmtConfig.scala#L123
I am not interested in maintaining a parallel copy of that file (and nested classes) in a reference.conf. Same applies to the style overlays.

> using += instead of inventing align.tokens.add

I agree this is unfortunate, but like I've said in other threads, align.tokens is intentionally not documented.

**Comment by olafurpg** [comment]
I'm working on adding Scala.js support now and it seems `.resolve(ResolveOptions.noSystem)` is not supported in https://github.com/unicredit/shocon

This means the next release of scalafmt will not support any advanced HOCON features, not even `+=`. Until someone contributes the resolve features to shocon, I'm gonna close this issue.

**Comment by olafurpg** [comment]
Things have changed a bit actually since scalafmt still uses typesafe/config on the JVM and will for the unforeseeable future. I'm open to add back `.resolve(ResolveOptions.noSystem)` here https://github.com/olafurpg/metaconfig/blob/b13e6bbbf5e0841f7ce00de1f54261415c26a8f8/metaconfig-typesafe-config/src/main/scala/metaconfig/typesafeconfig/TypesafeConfig2Class.scala#L48 which should get the previous behavior. This would allow you to spread configuration across files, scalafmt would still not provide a `reference.conf`, however

**Comment by olafurpg** [comment]
I've become more familiar now with cross-building to Scala.js and it's probably not an issue to support typesafe/config-specific features when running scalafmt on the JVM. I'm open to PRs if someone wants to refactor the configuration parts to support `+=`, `include`, maybe reference.conf. I understand these might be desirable features when you have multiple projects using scalafmt.

**Comment by olafurpg** [comment]
I have become convinced that the best long-term solution for cross-platform configuration is JSON. HOCON has a lot of nice things, but the lack of an official Scala-only implementation makes it unsuitable for tools that target Native + js. Now that native support is around the corner I plan to start phasing out hocon in favor of json.
