### ISSUE TITLE
Inconsistent alignment of `=` with named arguments

### ISSUE THREAD

**Issue by frosforever** [scalameta/scalafmt#850]
This template is a guideline, not a strict requirement.
- **Version**: 0.6.6
- **Integration**: sbt
- **Configuration**:
```
style = defaultWithAlign 

align.tokens.add = [
  { code = "=",   owner = "Term.Arg.Named"  }
]
```

## Steps

I ran scalafmt like this:

```bash
sbt scalafmt
```

## Problem

Scalafmt formats code like this:
```scala
package comexample

object Main {
  case class Foo(ab: String, abcde: Int, abc: String)

  Foo(
    ab = "a",
    abcde = 2,
    abc = "whatever"
  )
}
```

## Expectation

I would like the formatted output to look like this:
```scala
package comexample

object Main {
  case class Foo(ab: String, abcde: Int, abc: String)

  Foo(
    ab    = "a",
    abcde = 2,
    abc   = "whatever"
  )
}
```

## Workaround

I've found that by running `scalafmt` from within `sbt` multiple times in a row (~10), sometimes it will format as expected and sometime it will format without aligning. Seems like this formatting is not only not idempotent but also nondeterministic.

**Comment by olafurpg** [comment]
Thank you for reporting! Term.Arg.Named is disabled by default because it has several issues, including this one (which I've known about for a while).

I can't promise this will get fixed. For now, I recommend disabling custom vertical alignment for Term.Arg.Named.

If you are interested in taking a swing at this, I'm happy to give pointers. I suspect it may be related to this (evil) global cache here https://github.com/scalameta/scalameta/blob/fac0de590bf0633567a12ce38de2cf40c5b1b547/scalameta/tokenizers/jvm/src/main/scala/scala/meta/internal/tokenizers/PlatformTokenizerCache.scala#L15 but I haven't been able to validate if that's the case.

**Comment by frosforever** [comment]
Thanks for the guidance on this! Should I find the time I'd be happy to attempt a fix.

**Comment by marianogappa** [comment]
@olafurpg are there any plans to pick this up? This sort of alignment is very useful for readability and spotting bugs.

**Comment by olafurpg** [comment]
Pretty weird, I'm able to reproduce this bug with `style = defaultWithAlign ` if I run scalafmt **twice** but not once. When the config is only

```
align.tokens = [
  { code = "=",   owner = "Term.Arg.Named"  }
]
```
everything aligns nicely regardless how many times I run it.

@marianogappa no plans from my side to pick this up in the near future. My comment above still looks relevant, the alignment algorithm seems fine but something looks odd with equality when running scalafmt multiple times.

**Comment by olafurpg** [comment]
Please reopen if someone wants to take a stab at this
