### ISSUE TITLE
Ugly if-statement when inside a callSite Ctor

### ISSUE THREAD

**Issue by pjrt** [scalameta/scalafmt#866]
- **Version**: 0.6.6
- **Configuration**:
```
maxColumn = 80
```

## Problem

Scalafmt formats code like this:
```scala
new SomeClass(if (true) {
  Something
} else {
  SomethingElse
})
```

## Expectation

I would like the formatted output to look like this:
```scala
new SomeClass(
  if (true) {
    Something
  } else {
    SomethingElse
  })
```

**Comment by olafurpg** [comment]
I think this is a side effect of excluding the newlines inside the blocks in order to support common patterns like this

```scala
new Foo(new Bar {
  def bar = 2
}) 
```

See https://github.com/scalameta/scalafmt/blob/master/core/src/main/scala/org/scalafmt/internal/Router.scala#L622-L625

I guess we can skip the exclusion for Term.If or only trigger the exclusion for refinement types.

**Comment by sjrd** [comment]
> or only trigger the exclusion for refinement types.

It's also and more importantly for function literals, as well as simple blocks.

I would suggest excluding control structures: if, while, do..while, for and try.

**Comment by pjrt** [comment]
@olafurpg I got around this by just using `{}` in such cases. It isn't an actual solution but I probably won't be fixing it. Your call on whether to close this one.
