### ISSUE TITLE
Possible scalafmt (cli) interface changes

### ISSUE THREAD

**Issue by pjrt** [scalameta/scalafmt#875]
Currently the cli is a bit confusing when it comes to changing single files.

* Calling `scalafmt` (no args) will change all files recursively from where scalafmt is called. 
* Calling `scalafmt -f <file>` will not change the file, but will instead print to stdout the formatted files
    * Also, `<file>` is a list of comma separated files, which is odd
* Calling `scalafmt -i -f <file>` will change the files "in place" (ie: not print it to stdout but actually change the file)
* Calling `scalafmt` will change files in place, but adding ANY flag (eg: `--quiet` or `--non-interactive`) will cause it to print to stdout

I personally find this confusing. 

Proposal:

Require at least one file to be passed to scalafmt. If any of the files passed is a directory, the search recursively for scala files and format them in-place. We could add a new flag for the "output to stdout" case. 

`scopt` already supports such a feature. from their README:

```
arg[File]("<file>...").unbounded().optional().action( (x, c) =>
    c.copy(files = c.files :+ x) ).text("optional unbounded args")
```

Changing the `.optional()` to `.required()` would produce what the proposal would need.

**Comment by pjrt** [comment]
> Require at least one file to be passed to scalafmt

Ofc we could just say "if no files are passed, then assume `./`". Using `.optional()` would do that.

**Comment by olafurpg** [comment]
I apologize for how slow I've been at responding to this issue. Thank you for bringing this up.

I whole-heartedly agree that it would be nice to make the `-f` flag optional. The only reason it's not like that is because I couldn't figure out how to do with scopt.

> Require at least one file to be passed to scalafmt. If any of the files passed is a directory, the search recursively for scala files and format them in-place. We could add a new flag for the "output to stdout" case.

I like the idea of spec-ing something consistent. The current design is the result of random design choices that were made from release to release. However, we need to make sure that what we come up with plays nicely with `project.git` and `project.exclude/includeFilters`.

I propose that
- `project.git` is implemented as an `includeFilter`
- every candidate file must match includeFilters AND not match excludeFilters
- and as you say, if no directory is passed, then assume `./`. This keeps compatibility with the current `./scalafmt` interface which is how I run scalafmt 99% of the time tbh

**Comment by dwijnand** [comment]
Came to file something like this. I often do this:

```
$ scalafmt main/src/main/scala/sbt/EvaluateTask.scala
Error: Unknown argument 'main/src/main/scala/sbt/EvaluateTask.scala'
Try  for more information.
Exception in thread "main" org.scalafmt.Error$UnableToParseCliOptions$: Failed to parse CLI options
	at org.scalafmt.Error$UnableToParseCliOptions$.<clinit>(Error.scala)
	at org.scalafmt.cli.Cli$.mainWithOptions(Cli.scala:64)
	at org.scalafmt.cli.Cli$.main(Cli.scala:58)
	at org.scalafmt.cli.Cli.main(Cli.scala)
```

My wishlist is:
* keep `scalafmt` doing what it does now
* allow `scalafmt <files>` (i.e make `-f`/`--files` the implicit default)
* flip the default on `-i`/`--in-place`, so just defining a file will format it in place, and you can opt-out with some `-o`/`--stdout` or something.

I expect the last one is hard due to the migration path required..

**Comment by pjrt** [comment]
@olafurpg I can do this, but when would we want this? It is a major interface change so idk if we want to align it with v1.0 (and anything else happening at that point).

**Comment by olafurpg** [comment]
@pjrt That would be awesome if you could take a stab at this.

I propose that instead of `-i` or `-o` we do the same thing as `--write-mode` in rustfmt https://github.com/rust-lang-nursery/rustfmt#running 

- @pjrt if you can get this PR ready before 0.7.0 (I suspect it will take at least one more week to iron out a few remaining issues), then we can make the default `--write-mode=overwrite`. We document this breaking interface change in the changelog
-`-i` becomes an alias for `--write-mode=overwrite` (up for debate, maybe we should just remove it altogether)
- `--stdout` becomes alias for `--write-mode=display` (up for debate)
- If this PR doesn't make it before 0.7, we can still merge it but set `--write-mode=display` as default. Then we change the default to `replace` in 1.0 (or 0.8 if 1.0 delays further) 

To start with we can have only be two values for `--write-mode`, but if someone wants to add other modes like `diff` or `checkstyle` then that won't require an interface change.

**Comment by pjrt** [comment]
Sure, I'm not too familiar with rustfmt but a quick look at it seems reasonable. The pedantic in me wants to say that `display` and `stdout` aren't the same (if you pipe it, nothing is "displayed") but we can ignore that guy :).

**Comment by olafurpg** [comment]
I'm OK with stdout instead of display. I agree with you :)

**Comment by olafurpg** [comment]
@pjrt Actually, as soon as we get these cli changes in I'm happy to publish a 1.0.0-M1 and skip 0.7 entirely, what do you think? I'd like to remove a few options before cutting 1.0.0 final, but no new features. I don't want to start with #917 before releasing 1.0.

**Comment by pjrt** [comment]
@olafurpg That works out.

**Comment by pjrt** [comment]
Added another confusing part (having to do with flags).

**Comment by pjrt** [comment]
Ok, so I hadn't noticed that `project.git` only works when you pass no arguments to `scalafmt`. 

This makes things a bit more complicated. Should `scalafmt ./` respect project.git too? I would think not since any file can be passed in (even ones that are ignored by git). 

What do you think @olafurpg ? We could keep the current git interaction when doing `scalafmt` and ignoring it when doing `scalafmt ./` but that means one isn't an alias of the other. And we would need to make that clear in the docs.

**Comment by olafurpg** [comment]
Good observation @pjrt, I had forgotten that. Yes,  `scalafmt ./` should not respect `project.git` IMO.

The current cli flag semantics are kind of ad-hoc and complicated to explain. I am open to make some breaking changes to clean things up for v1.0 if you have suggestions to make this part more intuitive. For example, maybe

- the current `scalafmt` should be a command: `scalafmt project`
- `--test` could also be a command `scalafmt test`. In fact, do we need `--write-mode` when we have commands?  
- `scalafmt help` 
- `scalafmt print` instead of --stdout
- the default command (no command, if there is one in scopt) could be `write`

Just brainstorming.

**Comment by pjrt** [comment]
Commands would be odd since, for the most part, we are always doing the same thing: formatting (to stdout or in-place). Commands, like `git`, imply a multitude of options and actions. 

Here's an idea:

We keep the current flag-based system but add a new flag called `--git=[true|false]`. If the `project.git` isn't set, then we assume "no git" (as it is currently). 

If `project.git=true`, we change the way we do directory searches. So if someone passes `scalafmt somedir/`, when fetching the files we do `git ls-files someDir` (we currently use ls-tree, but the flags we pass make it behave like ls-files). This means that `scalafmt ./` will behave in the same way as `scalafmt`. 

However, if the user passes a file (not a directory) then we just accept it (assuming it is scala and all that jazz). 

If `project.git=false` (or not set) then we fall back on the normal directory recursive search. 

Users can enable and disable the git search via `--git=[true|false]`. 

A note on write-mode: I've already written it but the more I look at it, the more I think we should just have a `--stdout` and a `--in-place` (with `--in-place` being the default).

**Comment by olafurpg** [comment]
> Commands would be odd

Fair enough, it would be quite a drastic change as well for questionable gains.

> A note on write-mode: I've already written it but the more I look at it, the more I think we should just have a --stdout and a --in-place (with --in-place being the default).

I thought about this too and I agree, at least from the UI side. On the implementation side, I'm open to keep `WriteMode` as a field in CliOptions which is an enum/ADT of `StdOut` and `InPlace`. That could make it easier to extend and maintain. Either way, I'll leave it up to you to decide which approach you prefer, but --stdout and --in-place get my 👍 

> We keep the current flag-based system but add a new flag called --git=[true|false]. If the project.git isn't set, then we assume "no git" (as it is currently).

That is a great way to look at it, I really like that makes `scalafmt` and `scalafmt ./` the same if `project.git = true`. On the implementation side, what do you think of doing it in a similar way as WriteMode? We can have a `FileSearch` enum/ADT with options  `ScalaFiles` as default (filter out non-scala files, recurse on directories), `Git` (ls-files). One potential extra FileSearch could be `Exact` (format all arguments as files, fail on directories).

**Comment by pjrt** [comment]
@olafurpg and I chatted in Gitter and came up with the following confusion in the CLI interface. This one has to do with the way git is used to fetch files and how we determine whether a file can be formatted. 

Currently, the CLI (and config) has two ways of fetching files to format: plain-old directory recursion and calling `git ls-tree`. It also has a way to exclude files via `--exclude` (`project.excludeFilters` in the config). 
In the config it also has another option called `project.includeFilters`. 

The confusion that was found has to do with how `includeFilters` work. `excludeFilters` is pretty straight forward and there is no ambiguity there, but `includeFilters` is confusing since it makes it seem like you can "force" scalafmt to format certain files, and that's true, but it ONLY does it for files that had already been fetched. 

For example:

```
project.git = true
includeFilters = [.git/someFile]
```

This would make it *seem* like `.git/someFile` would be formatted, but it won't because `.git` won't be searched by `git ls-tree` (which is what we use to find files when `project.git=true` is set. 

In reality, `includeFilters` ought to be called `canFormat` since that's what it is trying to replicate. For example:

```
project.git=true
project.canFormat = [*.sbt, *.scala, *.scala.html, etc]
```
It is questionable whether we should allow a regex here. Why not have a list of file extensions? (do we expect people to place `project.canFormat = [someScalaFile]`? ie: a full file with no extension?

We could also have an `forceFormat` for files which fall outside of `git ls-tree`, but the usability of such a thing is questionable (why do you care if a file outside of your version control is formatted?). Until such a need becomes obvious I see no reason to add it.

-----------------

@olafurpg we talked about something related to `diff` but I can't recall. I think the issue was that I was proposing `forceFormat` but after writing this I realize that `forceFormat` is pointless. So that means that my main issue with `project.includeFilters` is just its name and how it is passed (a regex). But to be honest I can just ignore (doesn't bug me that much). 

There was also talk about just removing the `git` functionality and allowing plain bash to do its thing. I am not opposed to that idea but I'm also not proposing it (neutral).

**Comment by pjrt** [comment]
Another confusing part: why does `--diff` call against a branch? (by default `master`). 

I feel `scalafmt --diff` should call against the current branch.

**Comment by olafurpg** [comment]
Thank you for summarizing our discussion @pjrt 

I see now how `project.includeFilters` can be confusing. It is intentional that `.git/someFile` is not formatted, since `includeFilters` is only meant to *filter* the fetched files, not fetch new files. The name is used by sbt in a similar context: http://www.scala-sbt.org/0.13/docs/Howto-Customizing-Paths.html#Include%2Fexclude+files+in+the+source+directory In scalameta/scalameta we use `project.includeFilters` to run scalafmt on a subset of our modules, see https://github.com/scalameta/scalameta/blob/1dea2184cd7f8d659e34a9a1cae9448851bca104/.scalafmt.conf#L4-L13 For this use-case, I think `canFormat` would be a confusing name. (PS. We don't use `project.git=true` there, but we should IMO in order to skip walking through directories like `target/`)

Would `project.filter.include/exclude` be a better name for `project.includeFilters/excludeFilters`? If it doesn't bug you, then I propose to keep it unchanged.

> We could also have an forceFormat for files which fall outside of git ls-tree, but the usability of such a thing is questionable

I agree. I don't see a use-case for such a feature either, you can skip `project.git=true` in that case.

> Why not have a list of file extensions?

I feel that would be unnecessarily limiting compared to a full regex. I'd like to get away with as little new vocabulary as possible (not doing such a great job with style options here 😞 ).

> There was also talk about just removing the git functionality and allowing plain bash to do its thing. 

After some thinking, I would like to keep GitOps. I use the feature myself and it find it helpful. Baking this functionality into the cli makes more sense on the JVM compared to native binaries like rustfmt or clang-format.

> Custom extensions with `canFormat`.

I propose we keep the internal `canFormat` hard-coded to `.scala` and `.sbt` files. We can fix this in a separate issue. I've considered adding arbitrary support for `&&` and `||` combinators to make include/excludeFilters be able to handle rules like "format all .scala files AND that are in this directory".

>  why does --diff call against a branch?

Because I sometimes have multiple unformatted commits on a single branch. Diffing against HEAD is a special case which can be accomplished with `--diff-branch HEAD`. 

--

I'm eager to see your PR @pjrt! 😄

**Comment by pjrt** [comment]
Well my main issue with the diff thing is that `git diff` and `scalafmt --diff` don't act on the same items (since `git diff` is short of `git diff HEAD`). Also, `master` is a bit arbitrary. I've work for places where `dev` is the `main` branch, while `master` may be updated rarely if at all. 

Additionally, why `--diff` and `--diff-branch`? Why not just have `--diff=[branch]` where `branch` can be omitted?

Anyways, we don't need to deal with that in this PR, I'll keep it as it is for now. 

--

It is coming, code is done but need to update the tests. Sorry I've been so slow, been busy these past couple of weeks.

**Comment by pjrt** [comment]
@olafurpg re: includeFilters

We respect `includeFilters` when doing `scalafmt --diff` and when calling `scalafmt` (no params or flags). But it doesn't when calling `-f`. This seems to be an oversight, no?

**Comment by olafurpg** [comment]
when the user passes `-f` then I don't think we respect includeFilters/excludeFilters. The idea was to allow you to manually format file paths that are excluded by the configuration. However, I can see this complicating bash scripts that do something like `scalafmt -f $(git diff ...)`. I have considred adding a `--skip-filters` flag (or similar) to say "trust me, I want to format this file". WDYT?

**Comment by pjrt** [comment]
I do agree with any flags that allow to override the `.scalafmt.conf`. 

But for this PR, we could start to respect it for normally passed files (which now mean `scalafmt file1 file2`) BUT if `file1` or `file2` is a file (not a directory) then we can just format it (chance are that the user wants that file formatted). 

But this does create another "if this, then that" situation that *may* be confusion.
