### ISSUE TITLE
Case matches with danglingParens (over the maxColumn limit) look ugly

### ISSUE THREAD

**Issue by pjrt** [scalameta/scalafmt#955]
```
maxColumn = 80

style = default
docstrings = JavaDoc
danglingParentheses = true
indentOperator      = spray
align.openParenCallSite = false
align.openParenDefnSite = false
importSelectors = singleLine
rewrite.rules = [SortImports]
continuationIndent.callSite = 2
continuationIndent.defnSite = 4
continuationIndent.extendSite = 2
optIn.breakChainOnFirstMethodDot = true
verticalMultilineAtDefinitionSite = true

spaces {
  inImportCurlyBraces = true
}

project.git = true
```

## Problem

Scalafmt formats code like this:
```scala
inside(ConfigValidation.validateConfig[TestConfig](conf)) {
        case Invalid(
            ConfigReaderFailures(
              NoValidCoproductChoiceFound(_, None, Some(“logging.log-level”)),
              List.empty
            )
            ) =>
```

## Expectation

To be honest, I think we should just ignore dangling parens when it comes to case matches. I don't see any case where it won't be ugly

```scala
inside(ConfigValidation.validateConfig[TestConfig](conf)) {
        case Invalid(
            ConfigReaderFailures(
              NoValidCoproductChoiceFound(_, None, Some("logging.log-level")),
              List.empty)) =>
```

**Comment by olafurpg** [comment]
I agree the floating `)` is weird. This only seems to be a problem with `danglingParens=true`, in the default style you can opt-out of it. I think it would make sense to make it possible to exclude the dangling parenthesis from from `Pat` positions, with a check that `!leftOwner.is[Pat]` https://github.com/scalameta/scalafmt/blob/978c3507af4a30d250d8ededca4ad0fd280771c3/scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala#L604. We could make the setting an enum instead of Boolean, to keep support for the old behavior. I don't use the setting personally so I'll leave the call to you @pjrt.

A note on the indent, the case guard is indented by 2 extra spaces avoid confusion with the case body

```diff
  case x @ Foo(1111, 1111)
+     if true =>
-   if true =>
    danger()
```

**Comment by olafurpg** [comment]
I agree the indentation for long case patterns is ugly. It's not ugly enough though to force me to fix this though. Should we close @pjrt ?

**Comment by pjrt** [comment]
Since there's a workaround, I guess we can close it.
